### ISSUE TITLE
TypeError: Cannot read property 'timeData' of undefined when I try to send a request

### ISSUE THREAD

**Issue by LeanKhan** [hoppscotch/hoppscotch#1449] opened 2021-01-28 22:15 UTC
**Describe the bug**
I can't send requests. I am getting "TypeError: Cannot read property 'timeData' of undefined (press f12 for details)" when I hit "send".
I got this from the Console:
TypeError: Cannot read property 'timeData' of undefined
    at b0b09fe.modern.js:1
    at Generator.next (<anonymous>)
    at r (1322bd1.modern.js:2)
    at l (1322bd1.modern.js:2)

**To Reproduce**
1. Try any address in the URL field
2. Click "Send"
3. See error toast popup

**Expected behavior**
It should send request to address.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Microsoft Edge (Chromium)]

**Comment by AndrewBastin** [comment] 2021-01-28 23:31
@LeanKhan are you using the browser extension ? Have you enabled the proxy ? If you are using the extension, what is the version number.

**Comment by LeanKhan** [comment] 2021-01-28 23:39
No I'm not using the browser extension and not using a proxy. Just plain
website

**Comment by AndrewBastin** [comment] 2021-01-29 00:30
Hmm interesting.

I can't seem to reproduce the bug from my end.

But I will have a look into what the issue might be

@liyasthomas Axios Strategy issues ?

**Comment by liyasthomas** [comment] 2021-01-29 00:39
I can't reproduce this issue from my end too.

**Comment by liyasthomas** [comment] 2021-01-29 02:17
@LeanKhan
An issue with Proxy mode has been identified. We're working on a fix now. Please turn off Proxy mode from [Settings](https://hoppscotch.io/settings). Let me know if the issue still exists when proxy turned off.

**Comment by LeanKhan** [comment] 2021-01-30 22:14
Hello, @liyasthomas thanks, after turning off proxy the requests work. But for one of my APIs (https://flw-rule-validation.herokuapp.com/) it was throwing a CORS error. I'm not sure if it is on my end or not. Nice work anyway 👍

**Comment by LeanKhan** [comment] 2021-01-30 22:14
Sorry I'm not sure if I should close the issue...

**Comment by AndrewBastin** [comment] 2021-01-30 23:38
Umm, you don't need to close the issue because the proxy not working is an ongoing bug that both of us are looking into fixing.

The CORS issue is a problem when you are running without the proxy. You can use the browser extension instead to override the CORS and work with your APIs. You can find the links to get to the extension from the README. 

Sorry for the inconveniences caused @LeanKhan

**Closed** 2021-01-31 02:49 UTC
Labels: bug

**Comment by raschmitt** [comment] 2021-02-14 02:27
Has any fix on the proxy issue been released so far?

**Comment by liyasthomas** [comment] 2021-02-14 03:00
Yes, it's been fixed.
