### ISSUE TITLE
[feature]: Drag and drop not working on desktop app

### ISSUE THREAD

**Issue by baek-sang** [hoppscotch/hoppscotch#3519] opened 2023-11-09 07:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

<img width="418" alt="hop move" src="https://github.com/hoppscotch/hoppscotch/assets/69100154/4ffe4164-7bda-452a-ab97-5ebb097b94d2">

Collections, folders, and requests move freely between each other. (drag&drop, edit)

### Why should this be worked on?

.

**Comment by liyasthomas** [comment] 2023-11-09 07:49
Have you faced any errors/bugs with collection/request re-ordering?

You can reorder collections and requests, I couldn't reproduce any bugs in this section.

**Comment by pXius** [comment] 2023-11-23 13:28
Same issue,

Can reorder in browser not on desktop app.

hoppscotch: 23.8.4-1

Installed via `brew`

**Comment by wddddw** [comment] 2023-12-20 03:02
It works

**Comment by liyasthomas** [comment] 2023-12-20 03:24
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Feel free to reach out if you encounter any further concerns.

**Closed by liyasthomas** 2023-12-20 03:24 UTC
Labels: bug, desktop
