### ISSUE TITLE
[bug]: I think there is a problem with saving state

### ISSUE THREAD

**Issue by hckhanh** [hoppscotch/hoppscotch#2495] opened 2022-07-09 10:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

You can watch my recorded footage to get an idea about this bug.

[e36f6add-238e-4156-8bf1-00f28dd0d149.webm](https://user-images.githubusercontent.com/6380436/178101035-d9996048-a647-48a3-bb03-ea074a9c13f7.webm)

The saving state did not reset after rejecting the unsaved changes

### Steps to reproduce

Click to another request after rejecting unsaved changes.

### Environment

Production

### Version

Cloud

**Comment by WaylonOKC** [comment] 2022-07-14 16:09
I think this may be leading to the random issue that I'm seeing where saving a change to an API overwrites the previous API effectively deleting one (the previous api) and making a duplicate of the other (the one currently being saved).

**Comment by gabrielmdu** [comment] 2022-07-18 14:11
Isn't this the same problem addressed in #2324?

**Comment by liyasthomas** [comment] 2022-07-26 01:20
cc: @AndrewBastin, @nivedin

**Comment by AndrewBastin** [comment] 2022-07-28 12:14
As of e9576dd33962d675978be6e5461f9303b811abae....

I have implemented the fix for when there is no save context (no green dot) and you select a request which has no difference between the contents in the editor.

For other cases, it is still marked as an intended behavior. Closing the issue, but welcoming for conversations.

**Closed** 2022-07-28 12:14 UTC
Labels: bug, need testing
