### ISSUE TITLE
[feature]: Disable following 302 redirects

### ISSUE THREAD

**Issue by drilus** [hoppscotch/hoppscotch#3426] opened 2023-10-05 21:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I have an authorization endpoint that returns a code within a "Location" header. The response is also a 302. There doesn't seem to be any way to disable following the 302 thus it seems impossible for me to see the headers before being redirected.

### Why should this be worked on?

For some reason, developers introduce auth keys via a response header and 302 status code.

**Comment by liyasthomas** [comment] 2023-10-06 04:28
We've an existing issue ticket for the same hence closing this one.
Possibly a duplicate of #2095.

**Closed by liyasthomas** 2023-10-06 04:28 UTC
Labels: feature
