### ISSUE TITLE
[feature]: Automated parsing of parameters from a prefilled URL

### ISSUE THREAD

**Issue by BladedShip** [hoppscotch/hoppscotch#3459] opened 2023-10-17 07:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When pasting a URL that already contains URL parameters, Hoppscotch will automatically parse the URL and add the appropriate parameters to the interface. Currently, when a URL is pasted in, the parameters within the Hoppscotch app remain empty, but the URL still contains parameters within it. This feature would automatically move all those parameters into the interface, extracting them from the URL. Optionally, it can also update the URL based on the parameters and display the final request URL for reference.

# Current Behavior:
<img width="946" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/67158370/d96c8d6d-4ceb-4e06-a27e-64d2844057f8">

# Feature:
<img width="942" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/67158370/f7efff7a-a048-4b24-b579-3905713ca67f">

### Why should this be worked on?

- Improved User Experience: Automatically parsing URLs could mean that users no longer have to manually transfer over the URL params from a finished URL, helping reduce user error
- Efficiency: It would help to save some time by removing the time taken to redefine all the URL params
- Better Clarity: Having a finished URL shown upfront can help users review and understand the exact request being made

I recently switched from using Postman to Hoppscotch, and this is one of the only features that I seem to miss from it. I would really like to work on it myself, and it would be appreciated if someone could help me with this.

**Comment by thetronjohnson** [comment] 2023-10-17 16:45
Hi @BladedShip if you select the entire URL, you should be able to use our context menu feature to quickly move the parameters in the URL to the parameters section.

<img width="1054" alt="Screenshot 2023-10-17 at 10 10 41 PM" src="https://github.com/hoppscotch/hoppscotch/assets/22194802/c017ae84-f40a-4a56-989d-504d84a8105e">

<img width="1054" alt="Screenshot 2023-10-17 at 10 12 04 PM" src="https://github.com/hoppscotch/hoppscotch/assets/22194802/ccb1af63-9b07-4c92-ad5b-fb2953bd2e91">

**Comment by BladedShip** [comment] 2023-10-17 16:56
What I had in mind was for it to automatically perform this action when you paste a link. After that, if the user decided to remove/backspace the URL params from the endpoint, the same change would reflect in the URL parameters tab. I believe this would provide a more developer-friendly experience, rather than having it hidden in a context menu.

**Comment by liyasthomas** [comment] 2023-10-17 17:20
@BladedShip thanks for your feedback. As mentioned in https://github.com/hoppscotch/hoppscotch/issues/2353#issuecomment-1135000877

> Our idea with the params section and the URL is that, we consider the params defined in the URL bar as constants and params defined in the params section as things that should be modified.

As of now, you can move parameters from the URL input field to the "Parameters" section by selecting desired parameters or the entire URL and clicking "Add to parameters".

_Possibly a duplicate of #2353, #2894, and #2227 hence closing._

**Closed by liyasthomas** 2023-10-17 17:20 UTC
Labels: feature
