### ISSUE TITLE
runing in dev mode shows app always in loading state

### ISSUE THREAD

**Issue by sourabhmandal** [hoppscotch/hoppscotch#1681] opened 2021-05-30 01:52 UTC
**Describe the bug**
while running the `npm run dev` and then launching `localhost:3000` in chrome. The loader keeps blipping infinitely.
**To Reproduce**
1. git clone https://github.com/hoppscotch/hoppscotch.git
2. npm install
3. npm run dev

**Expected behavior**
The app should launch and show a landing page.

**Screenshots**
![image](https://user-images.githubusercontent.com/39632788/120089395-6a7e4200-c117-11eb-9e91-a5954bcbce56.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: chrome
 - Version: chrome 89.0

**Comment by liyasthomas** [comment] 2021-05-30 03:04
Possible duplicate of #1661.
Please refer to https://github.com/hoppscotch/hoppscotch/issues/1661#issuecomment-844741363.

**Closed by liyasthomas** 2021-05-30 03:04 UTC
