### ISSUE TITLE
[feature]: Multitple Tabs for Requests

### ISSUE THREAD

**Issue by Skadarken** [hoppscotch/hoppscotch#2302] opened 2022-04-30 12:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I would like a single browser tab to be able to handle multiple requests using tabs in-app like Postman. 

### Why should this be worked on?

This would significantly cut down on the need to constantly switch between browser tabs and prevent clutter, especially when working on multiple projects.

Plus, a browser is not good for keeping more than 10 tabs open without losing sight of the requests and the browser tab does not show me which request it is either. Multiple tabs in-app would reduce confusion and speed up development and testing

**Comment by liyasthomas** [comment] 2022-04-30 12:15
Duplicate of #690, hence closing.

**Closed by liyasthomas** 2022-04-30 12:15 UTC
Labels: feature
