### ISSUE TITLE
Import OpenAPI yaml/json file as collection

### ISSUE THREAD

**Issue by Metal-joker** [hoppscotch/hoppscotch#1182] opened 2020-09-23 09:47 UTC
**Is your feature request related to a problem? Please describe.**
Some framework such as `fastapi` generated a `openapi.json`. I want to import this easily to hoppscotch

**Describe the solution you'd like**
Add a option to make import OpenAPI file possible

**Additional context**
None

**Comment by yashu2001** [comment] 2021-01-16 15:49
@liyasthomas I'm new here but would like to try my luck on adding this feature could you please guide me on how to get started.
Thanks

**Comment by liyasthomas** [comment] 2021-01-16 17:29
@yashu2001 yes sure. I'd love to help you out with this feature. Feel free to join any one of our communication channel on [Telegram](https://t.me/hoppscotch) or [Discord](https://discord.gg/GAMWxmR) and ping me.

**Comment by liyasthomas** [comment] 2021-01-20 02:51
Duplicate of #470 hence closing. Discussions will continue in the original thread.

**Closed by liyasthomas** 2021-01-20 02:51 UTC
Labels: feature
