### ISSUE TITLE
[bug]: Something went wrong with </>show code

### ISSUE THREAD

**Issue by somono** [hoppscotch/hoppscotch#4036] opened 2024-05-06 02:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when i use </>show code On Mac App(Apple Silicon) Something went wrong
![some](https://github.com/hoppscotch/hoppscotch/assets/37798868/e0a327fd-199a-4500-a44e-a81e999f8ccf)

### Steps to reproduce

![opt](https://github.com/hoppscotch/hoppscotch/assets/37798868/3bb725de-1f67-496e-b069-b632af10f926)
just click it

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment] 2024-05-06 03:01
Thanks for reporting this error.

We've identified the cause of this issue and opened a PR (#4033) to fix this. This will be patched in the next immediate release candidate.

_Possibly a duplicate of #4008._

**Comment by liyasthomas** [comment] 2024-05-11 07:19
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Closed by liyasthomas** 2024-05-11 07:19 UTC
Labels: bug, need testing
