### ISSUE TITLE
[bug]: Docker Compose Backend container always restarting

### ISSUE THREAD

**Issue by cristianorevil** [hoppscotch/hoppscotch#2999] opened 2023-04-18 08:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have cloned the repository, copied the .env.example file to .env and changed with custom settings

Running docker compose up -ad the backend container is build but continous restarting with following error:

hoppscotch-backend  | node:internal/modules/cjs/loader:958
hoppscotch-backend  |   throw err;
hoppscotch-backend  |   ^
hoppscotch-backend  | 
hoppscotch-backend  | Error: Cannot find module '/usr/src/app/dist/main'
hoppscotch-backend  |     at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
hoppscotch-backend  |     at Module._load (node:internal/modules/cjs/loader:803:27)
hoppscotch-backend  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
hoppscotch-backend  |     at node:internal/main/run_main_module:18:47 {
hoppscotch-backend  |   code: 'MODULE_NOT_FOUND',
hoppscotch-backend  |   requireStack: []
hoppscotch-backend  | }

### Steps to reproduce

Clone repository
Copy .env.example to .env
Execute docker compose up -d

### Environment

Production

### Version

Self-hosted

**Comment by balub** [comment] 2023-04-18 11:59
Hey @cristianorevil , before running the `docker compose up -d` can you run `pnpm i` .

**Comment by balub** [comment] 2023-05-09 07:48
@beerkeeper It seems that EACCES permissions errors have something to do with system permissions may I suggest you run the `pnpm i ` with `sudo` as in `sudo pnpm i` and try again.  You can refer to these [post](https://stackoverflow.com/questions/48910876/error-eacces-permission-denied-access-usr-local-lib-node-modules) and [this[(https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) from npm while we look into it.

**Comment by beerkeeper** [comment] 2023-05-09 10:23
> @beerkeeper It seems that EACCES permissions errors have something to do with system permissions may I suggest you run the `pnpm i ` with `sudo` as in `sudo pnpm i` and try again. You can refer to these [post](https://stackoverflow.com/questions/48910876/error-eacces-permission-denied-access-usr-local-lib-node-modules) and [this](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally) from npm while we look into it.

I can confirm that this does work! Just for anyone else that runs into this issue: You also need to install pnpm globally as the root user. I don't think it is best practice, but you mentioned that it is being looked into 👍🏻 

The steps (execute within the root of the project):
* `sudo npm i -g pnpm`
* `sudo pnpm i`
* `docker compose up` -> I didn't need to rebuild the backend image afterwards

**Comment by Number16BusShelter** [comment] 2023-05-11 17:14
it seems like using sudo is not a good practice. 
And why is it required to do install if this step is done on docker build?

**Comment by jackiewu** [comment] 2023-05-16 04:27
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current behavior
> I have cloned the repository, copied the .env.example file to .env and changed with custom settings
> 
> Running docker compose up -ad the backend container is build but continous restarting with following error:
> 
> hoppscotch-backend | node:internal/modules/cjs/loader:958 hoppscotch-backend | throw err; hoppscotch-backend | ^ hoppscotch-backend | hoppscotch-backend | Error: Cannot find module '/usr/src/app/dist/main' hoppscotch-backend | at Module._resolveFilename (node:internal/modules/cjs/loader:955:15) hoppscotch-backend | at Module._load (node:internal/modules/cjs/loader:803:27) hoppscotch-backend | at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) hoppscotch-backend | at node:internal/main/run_main_module:18:47 { hoppscotch-backend | code: 'MODULE_NOT_FOUND', hoppscotch-backend | requireStack: [] hoppscotch-backend | }
> 
> ### Steps to reproduce
> Clone repository Copy .env.example to .env Execute docker compose up -d
> 
> ### Environment
> Production
> 
> ### Version
> Self-hosted

my solution is comment the following line at docker-compose.yml, hope this can help you 
<img width="560" alt="image" src="https://github.com/hoppscotch/hoppscotch/assets/1164959/bee8b249-1d17-476b-9957-c157a0fbf1eb">
https://github.com/hoppscotch/hoppscotch/blob/d6c840011616317ba98f143da61b8f38bc1f5fc2/docker-compose.yml#L22

**Comment by aholeye** [comment] 2023-05-16 09:23
> 

When I execute `sudo pnpm i`, I encounter the following error.Do you know about this issue?
```
packages/hoppscotch-ui postinstall$ pnpm run build
│ > @hoppscotch/ui@0.0.1 build /Users/spike/github/hoppscotch/packages/hoppscotch-ui
│ > vite build
│ vite v3.2.6 building for production...
│ transforming...
│ ✓ 5 modules transformed.
│ [vite:dts] Start generate declaration files...
│ [vite:dts] A error occurred when transform code, maybe there are some inertnal bugs.
│ [vite:dts] Declaration files built in 2173ms.
│ [vite:dts] Unexpected token (6:2)
│ file: /Users/spike/github/hoppscotch/packages/hoppscotch-ui/src/components/smart/Anchor.vue:6:2
│ error during build:
│ SyntaxError: Unexpected token (6:2)
│     at instantiate (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:653:32)
│     at constructor (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:946:12)
│     at TypeScriptParserMixin.raise (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:3270:19)
│     at TypeScriptParserMixin.unexpected (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:3300:16)
│     at TypeScriptParserMixin.parsePropertyName (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:11847:18)
│     at TypeScriptParserMixin.parsePropertyDefinition (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:11710:22)
│     at TypeScriptParserMixin.parseObjectLike (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:11649:21)
│     at TypeScriptParserMixin.parseExprAtom (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:11159:23)
│     at TypeScriptParserMixin.parseExprSubscripts (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10872:23)
│     at TypeScriptParserMixin.parseUpdate (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10855:21)
│     at TypeScriptParserMixin.parseMaybeUnary (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10831:23)
│     at TypeScriptParserMixin.parseMaybeUnary (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9754:18)
│     at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10669:61)
│     at TypeScriptParserMixin.parseExprOps (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10674:23)
│     at TypeScriptParserMixin.parseMaybeConditional (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10651:23)
│     at TypeScriptParserMixin.parseMaybeAssign (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10612:21)
│     at TypeScriptParserMixin.parseMaybeAssign (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9701:20)
│     at /Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10582:39
│     at TypeScriptParserMixin.allowInAnd (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12257:12)
│     at TypeScriptParserMixin.parseMaybeAssignAllowIn (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10582:17)
│     at TypeScriptParserMixin.parseExprListItem (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12009:18)
│     at TypeScriptParserMixin.parseCallExpressionArguments (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:11064:22)
│     at TypeScriptParserMixin.parseCoverCallAndAsyncArrowHead (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10979:29)
│     at TypeScriptParserMixin.parseSubscript (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10914:19)
│     at TypeScriptParserMixin.parseSubscript (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9239:18)
│     at TypeScriptParserMixin.parseSubscripts (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10885:19)
│     at TypeScriptParserMixin.parseExprSubscripts (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10876:17)
│     at TypeScriptParserMixin.parseUpdate (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10855:21)
│     at TypeScriptParserMixin.parseMaybeUnary (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10831:23)
│     at TypeScriptParserMixin.parseMaybeUnary (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9754:18)
│     at TypeScriptParserMixin.parseMaybeUnaryOrPrivate (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10669:61)
│     at TypeScriptParserMixin.parseExprOps (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10674:23)
│     at TypeScriptParserMixin.parseMaybeConditional (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10651:23)
│     at TypeScriptParserMixin.parseMaybeAssign (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10612:21)
│     at TypeScriptParserMixin.parseMaybeAssign (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9701:20)
│     at /Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10582:39
│     at TypeScriptParserMixin.allowInAnd (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12252:16)
│     at TypeScriptParserMixin.parseMaybeAssignAllowIn (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:10582:17)
│     at TypeScriptParserMixin.parseExportDefaultExpression (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:13758:22)
│     at TypeScriptParserMixin.parseExportDefaultExpression (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9358:18)
│     at TypeScriptParserMixin.parseExport (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:13663:25)
│     at TypeScriptParserMixin.parseExport (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9341:20)
│     at TypeScriptParserMixin.parseStatementContent (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12661:27)
│     at TypeScriptParserMixin.parseStatementContent (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:9398:18)
│     at TypeScriptParserMixin.parseStatementLike (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12549:17)
│     at TypeScriptParserMixin.parseModuleItem (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12526:17)
│     at TypeScriptParserMixin.parseBlockOrModuleBlockBody (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:13121:36)
│     at TypeScriptParserMixin.parseBlockBody (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:13114:10)
│     at TypeScriptParserMixin.parseProgram (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12437:10)
│     at TypeScriptParserMixin.parseTopLevel (/Users/spike/github/hoppscotch/node_modules/.pnpm/@babel+parser@7.21.8/node_modules/@babel/parser/lib/index.js:12427:25)
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 5.6s
```

**Comment by webysther** [comment] 2023-05-29 19:45
I fixed this creating a LinuxServer based container with all services and rebuild when restart: https://github.com/webysther/hoppscotch

**Comment by webysther** [comment] 2023-05-29 19:46
[Related](https://github.com/hoppscotch/hoppscotch/issues/3092)

**Comment by forresthopkinsa** [comment] 2023-07-10 21:48
Unfortunately, running pnpm as root is not an acceptable solution in most environments. Can we figure out why it's trying to write to `../../../`? This is very weird behavior that seems specific to Hoppscotch

**Comment by AndrewBastin** [comment] 2023-09-06 16:06
Closing this issue due to inactivity. Please do check if the 2023.8.0 release has this issue still and reopen if so.

**Closed by AndrewBastin** 2023-09-06 16:06 UTC
Labels: bug, need testing, self host
