### ISSUE TITLE
Add file transfer options to hoppscotch for graphql!

### ISSUE THREAD

**Issue by simonsantan** [hoppscotch/hoppscotch#2008] opened 2021-12-12 06:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

We need actually a options to transfer file in graphql.

### Why should this be worked on?

When we build a graphql api, it really need to transfer file. As you know apollo studio also provide api playground. But there has no option to transfer file. That's why we have to find another ecosystem or graphql playground, that has file transfer system. It is the only features we are looking for a graphql playground.

We hope you take this as serious case! thank you.

**Comment by liyasthomas** [comment] 2021-12-12 06:17
Duplicate of #1902, hence closing.

**Closed by liyasthomas** 2021-12-12 06:17 UTC
Labels: feature
