### ISSUE TITLE
[bug]: Error in Windows Desktop App (when trying to "Show code")

### ISSUE THREAD

**Issue by bvwidt** [hoppscotch/hoppscotch#4026] opened 2024-05-02 07:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I open the Windows Desktop App (v2024.3.2) I don't see any error directly but when I open the DevTools I see an error in the Console.

![error](https://github.com/hoppscotch/hoppscotch/assets/2772161/a9fefd7d-4447-4ab7-b514-c96045d35343)

Further when I try to show the code of a request I get a message "Something went wrong" and I see another error in the Console like above whenever I click on _Send_ -> _Show Code_.

![something-went-wrong](https://github.com/hoppscotch/hoppscotch/assets/2772161/2be7129b-70a3-44ae-986b-dd28402d1f67)
![more-errors](https://github.com/hoppscotch/hoppscotch/assets/2772161/b754be4f-5cb8-46ae-b0be-e09abedbfa19)

I don't have these problems when I use the app in the browser (Vivaldi).

### Steps to reproduce

1. Click Send -> Show Code
2. See the error
3. Press `F12` to see the Dev Tools
4. Under Console see the error

### Environment

Production

### Version

Local

**Comment by AndrewBastin** [comment] 2024-05-03 09:50
Closing this issue as it is a duplicate of #4008

**Closed by AndrewBastin** 2024-05-03 09:50 UTC
Labels: bug, need testing
