### ISSUE TITLE
Dynamic environment variables

### ISSUE THREAD

**Issue by pikausp** [hoppscotch/hoppscotch#1468] opened 2021-02-05 10:54 UTC
Hello,

is it possible to dynamically set environment variables e.g. within tests, similar to Postman? Our use-case is to automatically set authentication token after calling sign-in/refresh endpoints and not having to manually copy and set the token.

Thank you for any tips

**Comment by liyasthomas** [comment] 2021-02-05 14:07
Possibly a duplicate of #1425 and #984

> Since this involves making two requests, adding token from first response to environment should be a manual process. Also you can make use of Authentication section to mention Bearer token after fetching the token first.

As of now, environment variables can't be changed from Tests script.

Refer: https://github.com/hoppscotch/hoppscotch/issues/1425#issuecomment-758806073

**Closed by liyasthomas** 2021-02-05 14:07 UTC

**Comment by tudordre** [comment] 2023-05-11 22:03
@liyasthomas was this developed? Wasn't able to find more info than here and this issue https://github.com/hoppscotch/hoppscotch/issues/984

**Comment by liyasthomas** [comment] 2023-05-12 02:51
Hi @tudordre, refer to our documentation to learn how to create environment variables from pre request scripts and tests: https://docs.hoppscotch.io/documentation/getting-started/rest/pre-request-scripts#setting-environment-variables#setting-environment-variables

**Comment by Muhammad-Mostafa** [comment] 2023-07-31 10:43
Hi @liyasthomasIs

Are there any updates about whether you guys added this feature of the ability to store the auth token in the environment variables. Can i write a script to store the auth token from login response to the environment variables?

I checked out your documentation, but didn't find a related something about this. thanks in advance.

**Comment by Muhammad-Mostafa** [comment] 2023-07-31 10:45
Hi @liyasthomas 

Are there any updates about whether you guys added this feature of the ability to store the auth token in the environment variables. Can i write a script to store the auth token from login response to the environment variables?

I checked out your documentation, but didn't find a related something about this. thanks in advance.

**Comment by liyasthomas** [comment] 2023-07-31 10:53
Hi @Muhammad-Mostafa, you can now create, update environment variables directly from Test scripts.
Documentation: https://docs.hoppscotch.io/documentation/getting-started/rest/pre-request-scripts#setting-environment-variables%23setting-environment-variables

**Comment by umardev500** [comment] 2023-11-16 00:55
> Hi @Muhammad-Mostafa, you can now create, update environment variables directly from Test scripts. Documentation: https://docs.hoppscotch.io/documentation/getting-started/rest/pre-request-scripts#setting-environment-variables%23setting-environment-variables

how to set automatically after login

**Comment by liyasthomas** [comment] 2023-11-16 02:36
[Setting Environment Variables from API Responses](https://docs.hoppscotch.io/documentation/features/scripts#setting-environment-variables-from-api-responses)

**Comment by Moni142002** [comment] 2024-09-18 07:23
Hii 
Is it possible to dynamically add a token to set an environment variable in Hoppscotch
var response = pw.response.json();
pw.env.set("token", "response.token"); 
I'm trying this one in a Pre-request Script but its not working as I expected
Pls suggest me some ideas....

**Comment by Moni142002** [comment] 2024-09-18 07:35
@liyasthomas  Tried but not working..
   I've reviewed the documentation, but it only shows how to add a random value to the URL. However, I want to dynamically extract a value from the request body and set it as an environment variable

**Comment by liyasthomas** [comment] 2024-09-18 07:40
Pre-request scripts run before executing the request.
Post-request tests run after executing the request.

If you want to access the response body from scripts, you need to add them to the Test scripts of the request so that it'll have access to the response context.

Can you add the scripts to tests and see if it works?

**Comment by Moni142002** [comment] 2024-09-18 07:49
@liyasthomas But its not working...I want to know..Is it possible to add token value dynamically to set environment variable when i sign In or sign up  in Hoppscotch..

**Comment by liyasthomas** [comment] 2024-09-18 07:53
I'm afraid that's not possible in Hoppscotch at the moment. But I'm curious, what is the use-case you're trying to achieve?

**Comment by Moni142002** [comment] 2024-09-18 08:33
{
  "status": true,
  "user": {
    "email": "abcdevht@dqitech.com",
    "phone": "630909088",
    "profilePicture": null,
    "profileComplete": false,
    "id": "66acb9ab5d60599ffc01ff45d"
  },
  "token": "66ea84e2963ea4daf30fa104|MTnvCGSpkDZWkwkZo47n9FOTIVenvoc5LPzADJNKFR1b000507"
} When I sign in or sign up, the token should be dynamically set as an environment variable..
