### ISSUE TITLE
[bug]: Duplication should work correctly for non-saved requests

### ISSUE THREAD

**Issue by vekien** [hoppscotch/hoppscotch#3594] opened 2023-11-25 00:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you create a request, then try duplicate it. You will get a duplication of it's last saved state instead of it's current state. this is really confusing. For example say you have:

Request: "Get from Twitter"

then you duplicate that and name it like "Post from twitter"

but you haven't saved so then you duplicate the "Post from twitter" you'll actually get the data and configuration from "Get from Twitter" because that is the last saved state.

If you make big changes to a request, then try duplicate, it will not have any of those changes until you Save _then_ duplicate.

### Steps to reproduce

1. Make a request
2. Do some changes to the request but don't save
3. Duplicate the request
4. The duplicated request will not have any of the changes you made.

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment] 2023-11-25 04:35
This is an intended behavior.

Duplicating the request from the collection level will only preserve the last saved changes, if you want to duplicate the request setup with unsaved changes you can right-click on the Tab Head and select "Duplicate Tab" as shown in the below screenshot; this will create a copy of the unsaved request in another Tab.

> [!Note]
> Since this new Tab has unsaved changes you might want to save it to the collection to preserve the changes.

<img width="1470" alt="Screenshot 2023-11-25 at 9 58 49 AM" src="https://github.com/hoppscotch/hoppscotch/assets/10395817/0de22352-7a3a-490a-ac87-56842e6c2a40">

Hope this resolves your question, hence I'm closing this ticket.

**Closed by liyasthomas** 2023-11-25 04:35 UTC
Labels: bug, need testing

**Comment by vekien** [comment] 2023-11-25 10:00
I think that is extremely bad design choose, because other clients don’t have this problem (I suppose they auto save)

this is just confusing.
