### ISSUE TITLE
[feature]: Does Hoppscotch have plans to support defining request and response parameter types and descriptions?

### ISSUE THREAD

**Issue by jingxiang** [hoppscotch/hoppscotch#3038] opened 2023-05-05 14:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Does Hoppscotch have plans to support defining request and response parameter types and descriptions?

### Why should this be worked on?

I want to include it as part of the documentation specification

**Comment by nguyennm96** [comment] 2023-05-24 02:08
Upppp

**Comment by fickleness-youth** [comment] 2023-07-05 09:35
This requirement is very practical and I hope it will be officially supported soon

**Comment by xhwsd** [comment] 2023-08-04 06:51
Hope for support

**Comment by liyasthomas** [comment] 2023-08-05 10:44
Possibly a duplicate of #2018, hence closing.

**Closed by liyasthomas** 2023-08-05 10:44 UTC
Labels: feature
