### ISSUE TITLE
Support importing Postman Environments

### ISSUE THREAD

**Issue by kiriti999** [hoppscotch/hoppscotch#1601] opened 2021-04-14 18:28 UTC
**Describe the bug**
Unable to import or delete environment json variables properly from postman

The imported env variables has blank labels and not able to delete them

**To Reproduce**
1. Go to environments
2. Click on imports and import a json
3. Imported variables doesn't have labels
4. Try to delete them. The model pop up "Yes" button doesn't work
5. Also unable to create the environment variables. (the save button doesn't work - see the last screenshot attached)

**Screenshots**
![image](https://user-images.githubusercontent.com/13074074/114760930-83a47c80-9d7d-11eb-89fe-2166b21d14a8.png)
![image](https://user-images.githubusercontent.com/13074074/114760967-8dc67b00-9d7d-11eb-88e3-2bc2381e0d6a.png)
![image](https://user-images.githubusercontent.com/13074074/114761772-910e3680-9d7e-11eb-9dff-5c12cef23272.png)
![image](https://user-images.githubusercontent.com/13074074/114764444-93be5b00-9d81-11eb-85bb-72eca35e57ee.png)

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome app]
 - Version [Version 89.0.4389.128 (Official Build) (64-bit)]

**Additional context**
I am trying to import this JSON file from postman:

```
{
	"id": "016d4d8f-10d9-40ad-9e95-502cfe2aa956",
	"name": "views v1 local",
	"values": [
		{
			"key": "URL",
			"value": "http://localhost:{{port}}/api/v1",
			"enabled": true
		},
		{
			"key": "envId",
			"value": "env1",
			"enabled": true
		},
		{
			"key": "orgId",
			"value": "org1",
			"enabled": true
		},
		{
			"key": "port",
			"value": "3000",
			"enabled": true
		},
		{
			"key": "email",
			"value": "kiriti.komaragiri@altusgroup.com",
			"enabled": true
		}
	],
	"_postman_variable_scope": "environment",
	"_postman_exported_at": "2021-04-14T18:07:35.034Z",
	"_postman_exported_using": "Postman/8.2.1"
}
```

**Comment by liyasthomas** [comment] 2021-04-15 01:48
Hi @kiriti999 
As of now, Hoppscotch Environment importer doesn't support Postman Environments completely. It's actually possible and I'll look into this implementation ASAP.

**Comment by kiriti999** [comment] 2021-04-26 17:17
Hi @liyasthomas Any update?

**Comment by liyasthomas** [comment] 2021-04-27 05:06
I suppose this will require some more time since the way Postman uses the environment variable notaions is different than that of Hoppscotch. In Hoppscotch we prefer `<<variable_name>>` whereas in Postman it's `{{variable_name}}` notation. We'll look into this on a later period. Thanks for the patience.

**Comment by LordNoteworthy** [comment] 2021-09-18 03:59
Would be lovely to have this one working. Got the same issue, blank urls.

**Comment by deepto98** [comment] 2021-09-30 05:41
@liyasthomas Hi, this feature seems interesting to me. I have used Vue in the past, and use postman too. If this isn't assigned already, can I work on this?

**Comment by liyasthomas** [comment] 2021-09-30 06:09
Hi @deepto98, thanks for showing interest in contributing to Hoppscotch. You're free to work on this. Let us know if you've any doubts. Assigning this to you.

**Comment by deepto98** [comment] 2021-10-02 20:26
@liyasthomas I just set up project locally and am trying to reproduce the issue, strangely though, for me the import environment seems to be working properly, I tried with a new json export from postman as well as the json that you had provided here. Label, delete and save, all seem to be working. Am I missing something?

**Comment by jorgetovar** [comment] 2021-11-17 14:08
@deepto98 could you please link the pull request? I want to contribute without duplicating the work

**Comment by rakshit087** [comment] 2021-12-07 04:46
It seems to work for me as well. 

![image](https://user-images.githubusercontent.com/50898928/144966471-d1f5ebfa-0066-41d7-84ae-c88c0285e447.png)

I am using the same json file as @kiriti999. 

I also found this function
```
importFromPostman({ name, values }) {  
      const environment = { name, variables: [] }  
      values.forEach(({ key, value }) =>  
        environment.variables.push({ key, value })  
      )  
      const environments = [environment]  
      this.importFromHoppscotch(environments)  
}
```
This function is executed if `importFileObj._postman_variable_scope === "environment" || importFileObj._postman_variable_scope === "globals"` which seems to work for any postman environment.

Can someone confirm? Let me know if something is wrong with the function, would love to contribute 👽

**Comment by kritikmodi** [comment] 2021-12-07 12:23
Hi @deepto98 , is the issue resolved or are you working towards developing the solution as of now?

**Comment by samuelj90** [comment] 2022-02-24 07:04
@kritikmodi  This feature is working fine with latest version. 
@liyasthomas  I think this issue can be closed.

**Closed** 2022-02-24 15:51 UTC
Labels: feature, good first issue, future, neat for externship

**Comment by boardtc** [comment] 2022-09-08 11:30
I am using the windows app. In environments, I select Import / Export and choose "Import from Hoppscotch" (should this not be Import JSON? ) and select my Postman environment JSON file, which is the format as shown by the OP and contains 48 keys. Hoppscotch reports back that the file is imported and the environment shows in the list under global. However, clicking on it does not expand any keys at all and the environment does not appear to be accessible / imported at all. Any thoughts please?

**Comment by iDschepe** [comment] 2022-10-01 14:48
I was searching for a tool to convert postman exported environment zip file to a hoppscotch importable json file.
Unfortunately, I couldn't find, so I decided to share my results:

https://github.com/iDschepe/hoppscotch-transformer 

Feel free to contribute or give any feedback!
