### ISSUE TITLE
[feature]: Allow dragging requests to other collections to move them.

### ISSUE THREAD

**Issue by vekien** [hoppscotch/hoppscotch#3595] opened 2023-11-25 00:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently if you have 2 collections and try drag a request from Collection A to Collection B it will not work, the drag lights up as and the mouse hover kicks in, but you cannot drop the request into the collection.

The work around is:
- Click "Save As" then edit the collection in there.

You cannot even do Edit > X there is nothing there.

### Why should this be worked on?

Just think it's user friendly to allow it.

**Comment by advaith-unnikrishnan** [comment] 2023-11-25 01:45
This feature is already available in Hoppscotch. I tried dragging a request from one collection to another and it works. Could you check this [demo](https://www.loom.com/share/18c44a08d8cc4215ab0d1b945dbb89a7?sid=cac31f78-1059-4a76-8403-cc33d1a33c46) and try once again?

**Comment by vekien** [comment] 2023-11-25 01:48
Interesting, it’s definitely not working for me at all, using the Mac Desktop App… I will see if I can narrow down any details.

**Comment by liyasthomas** [comment] 2023-11-25 04:21
Thanks for testing out our alpha release candidates of the Hoppscotch desktop app.

This is a known issue which we're currently working on. Expect this to be solved in the next stable release.

This is also possibly a duplicate of #3519 hence closing. Kindly subscribe to the previous issue ticket to track the progress.

**Closed by liyasthomas** 2023-11-25 04:21 UTC
Labels: feature
