### ISSUE TITLE
Upload files in request

### ISSUE THREAD

**Issue by kaname-png** [hoppscotch/hoppscotch#1679] opened 2021-05-29 17:12 UTC
**Is your feature request related to a problem? Please describe.**
Solve the problem of making requests that require a file to be uploaded

**Describe the solution you'd like**
Enable file upload in the body of the POST request.

**Describe alternatives you've considered**
None.

**Additional context**
This is something that should be there since many api developers have endpoints where it is necessary to upload a file or several files in the request.

I have seen that this problem is since 2019 and they have not implemented it yet.

**Comment by liyasthomas** [comment] 2021-05-29 17:20
This feature has been implemented.
Instructions to upload file in `POST`, `PUT`, etc methods: https://github.com/liyasthomas/postwoman/issues/298#issuecomment-553470110

Possible duplicate of #298 - closing this issue.

**Closed by liyasthomas** 2021-05-29 17:20 UTC

**Comment by markblessing7** [comment] 2021-05-29 21:49
Enable file to upload.

**Comment by Rafay106** [comment] 2023-12-23 11:34
## How do I send text fields with an image field using multipart/form-data

- I am using multer in express js
- This is the request I am making using Hoppscotch
![image](https://github.com/hoppscotch/hoppscotch/assets/62567028/73f0172c-b32f-4741-a799-0ef6e02fcd3e)
- The image field is optional, if I don't send it I am getting "Unexpected end of form" error, this is not the case in Postman, if I uncheck image field then it is not giving any errors in postman
- Also I am sending some text fields in the above request, which is not reaching backend, the req.body object is empty
- This is not the case in postman, I am receiving all text fields in req.body
![image](https://github.com/hoppscotch/hoppscotch/assets/62567028/eff7cb96-2e0d-47c1-bd61-4db40b94fd7a)

### So overall I have 2 issues
1. Getting "Unexpected end of form" error when not sending file field
2. Can not send text fields together with field field in multipart/form-data
