### ISSUE TITLE
[feature]: What doesn't have a desktop version? I want to replace apifox

### ISSUE THREAD

**Issue by lifetin** [hoppscotch/hoppscotch#3147] opened 2023-06-17 06:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

What doesn't have a desktop version? I want to replace apifox

### Why should this be worked on?

What doesn't have a desktop version? I want to replace apifox

**Comment by liyasthomas** [comment] 2023-08-26 13:28
Possibly a duplicate of #3101, hence closing.

**Closed by liyasthomas** 2023-08-26 13:28 UTC
Labels: feature
