### ISSUE TITLE
pwa is not working

### ISSUE THREAD

**Issue by Tarrowren** [hoppscotch/hoppscotch#1304] opened 2020-10-27 09:06 UTC
This is the browser on my personal computer. Chrome  86.0.4240.111
![屏幕截图 2020-10-27 161819](https://user-images.githubusercontent.com/35626141/97277772-dba10280-1873-11eb-862a-0d0f79748467.png)

on my computer at work. Microsoft Edge 86.0.622.51
This computer used to have hoppscotch installed. I uninstalled the program, cleared the cache, and tried to reinstall, but had the same problem
![屏幕截图 2020-10-27 161645](https://user-images.githubusercontent.com/35626141/97277760-d8a61200-1873-11eb-8aea-a5b6c57c44de.png)

**Comment by liyasthomas** [comment] 2020-10-27 09:18
Possible duplicate of #419
Refer: https://github.com/hoppscotch/hoppscotch/issues/419#issuecomment-564321997

**Comment by Tarrowren** [comment] 2020-10-27 10:02
edge works but chrome doesn't work offline

**Comment by Tarrowren** [comment] 2020-10-28 06:18
I have cleaned everything, and tried with other computers, it still doesn't work.

**Comment by liyasthomas** [comment] 2020-10-28 06:20
Seems to be the issue is persisting. Reopening issue to track and fix. Thanks for letting me know.

**Comment by dgw** [comment] 2020-10-28 07:33
Inspecting the app manifest in Chrome's (86) dev tools shows a warning, Hoppscotch doesn't have a service worker. Apparently Chrome requires one, or it won't offer to install as a PWA.

**Comment by liyasthomas** [comment] 2020-10-28 11:48
This issue seems to be raised with disabling Workbox support in commit: https://github.com/hoppscotch/hoppscotch/commit/2ccd053b0a757b0db59299c6e6207236e7f3ed20

**Comment by liyasthomas** [comment] 2020-10-28 11:54
@dgw @Tarrowren can you confirm PWA is working in this deploy preview: https://deploy-preview-1306--hoppscotch.netlify.app
Just open the preview and see if you could install it as PWA.

**Comment by dgw** [comment] 2020-10-28 12:16
@liyasthomas Yep, the install action is present in the deploy preview. Perhaps not super helpful vs. your own confirmation (I'm also testing with Chrome on Win10), but still!

**Closed** 2020-10-28 12:19 UTC

**Comment by Tarrowren** [comment] 2020-10-28 14:24
Problem solved, thank you.
