### ISSUE TITLE
[feature]: Adding docs to endpoints

### ISSUE THREAD

**Issue by goktugerol-dev** [hoppscotch/hoppscotch#3598] opened 2023-11-27 22:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Adding docs and / or dev notes to related endpoints would be very useful.

### Why should this be worked on?

In complex projects, documentation is really necessary in team environments. To be able to use Hoppscotch easily with teams, it is necessary to add this feature.

**Comment by liyasthomas** [comment] 2023-11-28 04:10
We've plans to implement this feature.

Possibly a duplicate of #2018, hence closing.

**Closed by liyasthomas** 2023-11-28 04:10 UTC
Labels: feature
