### ISSUE TITLE
[bug]: desktop app crashes on launch on Windows 10

### ISSUE THREAD

**Issue by EngiN33R** [hoppscotch/hoppscotch#3533] opened 2023-11-10 08:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When trying to open the desktop app on Windows 10, the window appears for a split second and closes immediately. The process is also not running after the window closes. The same happens regardless of installation path (`C:\Program Files` or elsewhere) or whether I run the app as administrator.

https://github.com/hoppscotch/hoppscotch/assets/4773889/e5b08ce3-4a14-4c97-a051-43d218b0a202

### Steps to reproduce

1. Download desktop application installer
2. Go through the installation process
3. Attempt to launch the application

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment] 2023-11-10 09:02
Thanks for testing out the Hoppscotch Desktop App Alpha Release candidate and reporting the bug. We've prioritized fixing this issue in the next release candidate.

**Comment by liyasthomas** [comment] 2023-11-10 09:06
Since this issue is possibly a duplicate of #3524, I'd appreciate it if you could subscribe to that issue thread and track its progress there.

**Closed by liyasthomas** 2023-11-10 09:06 UTC
Labels: bug, need testing, desktop
