### ISSUE TITLE
[bug]: cURl paser body error

### ISSUE THREAD

**Issue by renmu123** [hoppscotch/hoppscotch#2424] opened 2022-06-13 03:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

when I import cURL, the bosy parse error.

### Steps to reproduce

Click to 'import cURL'
input: curl
```
curl 'http://api.test' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh,zh-CN;q=0.9,en;q=0.8,zh-TW;q=0.7,ja;q=0.6' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:8000' \
  -H 'Proxy-Connection: keep-alive' \
  -H 'Referer: http://localhost:8000/' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36' \
  --data-raw 'name=11&logistics_id=4&port_id=3' \
  --compressed \
  --insecure
```

Body was translate to "name: 11&logistics_id" instead of 
"name: 11 
logistics_id: 4
port_id: 3'"

### Environment

Release

### Version

Local

**Comment by AndrewBastin** [comment] 2022-06-13 06:15
cc: @kyteinsky

**Comment by John-Weak** [comment] 2022-06-15 06:06
Can you please assign this to me?

Also I was looking into tests of curl parser and found out that only one test contains  **--data-raw** ,
which is of type --data-raw '{"id":4,"crm_company_id":4,"industry_primary_id":2,"contacts":[]}',

Should I open a pull request to include the problematic type format:
 --data-raw 'name=11&logistics_id=4&port_id=3'

**Comment by kyteinsky** [comment] 2022-06-15 06:17
@John-Weak I am afraid that's not the issue here. The curl parser replaces all `--data-raw` tags with `-d` tags. But yeah one test sure is missing.

Last I looked into it there were issues with [this function](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/helpers/curl/curlparser.ts#L75) and [this block](https://github.com/hoppscotch/hoppscotch/blob/main/packages/hoppscotch-app/helpers/curl/curlparser.ts#L94-L101) getting executed. The problem is I don't remember why that else if block is there in the first place (@AndrewBastin would be smiling rn).

**Comment by John-Weak** [comment] 2022-06-15 07:12
As per my view I think this [pair function](https://github.com/hoppscotch/hoppscotch/blob/2d0bd48e0007009f7a2e945e606f25b8f8f59bb2/packages/hoppscotch-app/helpers/curl/curlparser.ts#L75-L87) is the issue,

After console logging the return value of this function for the [first test](https://github.com/hoppscotch/hoppscotch/blob/2d0bd48e0007009f7a2e945e606f25b8f8f59bb2/packages/hoppscotch-app/helpers/curl/__tests__/curlparser.spec.js#L9-L14):
![image](https://user-images.githubusercontent.com/18065510/173764581-ab4887a0-ee0a-49c2-8a91-8aeb2218cd5c.png)

But for problematic case:
![image](https://user-images.githubusercontent.com/18065510/173764740-7bceefbf-7d0a-42d2-9506-67828db3508d.png)

Am I on the correct path?

**Comment by kyteinsky** [comment] 2022-06-15 08:29
Yup totally! My guess is that the `Array.isArray` condition is not working properly. See if you can get part to work.

And bonus if you can find what that `else if` block does and place a small comment there.

**Comment by AndrewBastin** [comment] 2022-06-15 09:08
@John-Weak I am assigning this issue to you.

**Comment by John-Weak** [comment] 2022-06-16 04:53
Upon further inspection I think I will need to fix this [preprocess function](https://github.com/hoppscotch/hoppscotch/blob/2d0bd48e0007009f7a2e945e606f25b8f8f59bb2/packages/hoppscotch-app/helpers/curl/curlparser.ts#L30) so that It handles the case where **&** is presesnt 
(example name=11&logistics_id=4&port_id=3).

Since the [rawData](https://github.com/hoppscotch/hoppscotch/blob/2d0bd48e0007009f7a2e945e606f25b8f8f59bb2/packages/hoppscotch-app/helpers/curl/curlparser.ts#L48) is derived from [parser](https://github.com/hoppscotch/hoppscotch/blob/2d0bd48e0007009f7a2e945e606f25b8f8f59bb2/packages/hoppscotch-app/helpers/curl/curlparser.ts#L31),the only way to patch this is to modify the preprocess function

**Comment by kyteinsky** [comment] 2022-06-17 08:12
umm, the pre-processor is innocent here. Once you comment out the pairs function or make it return null or something falsy, and remove the else if block, you'll see this command would work flawlessly.

**Comment by kyteinsky** [comment] 2022-06-21 04:15
@John-Weak Still working on this one?

**Comment by John-Weak** [comment] 2022-06-21 04:17
> @John-Weak Still working on this one?

Yes,was busy the past few days.
Would look into this today

**Closed** 2022-07-28 15:54 UTC
Labels: bug, need testing
