### ISSUE TITLE
[bug]: Reclicking on the request currently selected/in use creates an entirely new unsaved instance of it

### ISSUE THREAD

**Issue by rofe-dl** [hoppscotch/hoppscotch#2625] opened 2022-08-30 12:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I have a request selected and in use, if I click on it again, the green dot goes away from it. Then, if I try to click on any other request or even the same request again, it prompts the save/discard box even though I made no changes to this request.

### Steps to reproduce

1. Select a request from the right panel.
2. Select it again and watch the green dot disappear.
3. Make no changes to the request.
4. Try to change to a different request or re-select the same one.
5. The discard/save prompt shows up.

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment] 2022-08-30 15:02
This is an expected behaviour.

**Comment by rofe-dl** [comment] 2022-08-30 15:47
Oh, okay. Is there a reason it's designed like that? Like, usually in programs when I click on an already selected item, it does nothing.

**Comment by AndrewBastin** [comment] 2022-09-05 09:07
Umm, it is because we wanted to provide a way for the user to detach the editing request in the session from the save location. This is a temporary hacky fix until we implement the tabs system.

See: https://github.com/hoppscotch/hoppscotch/issues/2431#issuecomment-1159400418

Closing as duplicate.

**Closed by AndrewBastin** 2022-09-05 09:07 UTC
Labels: bug, need testing
