### ISSUE TITLE
Send double request [bug]

### ISSUE THREAD

**Issue by Hernandiaz035** [hoppscotch/hoppscotch#1752] opened 2021-08-01 05:14 UTC
**Describe the bug**
Every request I make from Hoppscotch is sent twice, 10ms apart.

**To Reproduce**
1. Send a Request to a service in localhost 
2. Two requests are received instead of one

**Expected behavior**
Get one request.

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Brave Browser
 - Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (x86_64)

**Comment by liyasthomas** [comment] 2021-08-01 05:20
Deu to [`CORS`](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) policy in browsers, every request has a [Preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request).

Please make sure if the first request was a pre-flight request. [Read more about this behavior on StackOverflow](https://stackoverflow.com/questions/15381105/what-is-the-motivation-behind-the-introduction-of-preflight-cors-requests).

**Comment by Hernandiaz035** [comment] 2021-08-02 05:45
I appreciate your answer, I checked the documentation and it doesn't seem to be this, given that both requests are exactly the same method of my request (GET or POST), and Preflight should be a OPTIONS method request.

```
GET

[02/Aug/2021 05:26:54] "GET /circles/unam-fciencias/rides/ HTTP/1.1" 200 52
==================================================


GET

[02/Aug/2021 05:26:54] "GET /circles/unam-fciencias/rides/ HTTP/1.1" 200 52
```

**Comment by liyasthomas** [comment] 2021-08-02 06:30
Thanks for the detailed explanation. May I know whether if you've enabled any Hoppscotch interceptors in [Settings](https://hoppscotch.io/settings)? "Proxy mode" or "Extensions" ?

**Comment by Hernandiaz035** [comment] 2021-08-02 08:04
Since I'm testing something locally, I'm using the extension. But not any proxy.

![Screenshot](https://user-images.githubusercontent.com/6667132/127825732-e1e2c1bf-e81b-4161-8cb3-81855d213eb6.png)

**Comment by liyasthomas** [comment] 2021-08-02 08:05
Thank you, we'll look into it.

**Comment by Hernandiaz035** [comment] 2021-08-02 08:34
I just fixed it. I reckon that i had the PWA installed and both (PWA and website) were executing the request once I pressed Send.

I checked from a private window and realising that it worked fine, tried deleting all PWA installed. The only remaining problem is that i can't replicate the error.

Apologies for the concerns and thanks for your time.

**Comment by liyasthomas** [comment] 2021-08-02 08:47
Glad it worked out. Will track this behaviour and fix it as soon as possible.

**Comment by GorvGoyl** [comment] 2021-09-19 11:28
@liyasthomas  I'm facing the same issue i.e. every call I make from hoppscotch web client (using chrome extension) hits my local api server twice! Both the requests are of type `POST`. Issue doesn't happen if I use some desktop client like Postman. let me know if you need further details.
Also, should I post a new bug since you closed this issue?

**Comment by liyasthomas** [comment] 2021-09-19 11:30
@GorvGoyl please provide more details on the issue you're having.

**Comment by GorvGoyl** [comment] 2021-09-19 11:34
OS: Win 10
Browser: Microsoft Edge Browser
Version 93.0.961.47 (Official build) (64-bit)

@liyasthomas let me know if I missed something

**Comment by liyasthomas** [comment] 2021-09-19 11:40
@GorvGoyl let me know how to reproduce the issue. Also have you enabled any interceptor like browser extension / proxy?

**Comment by GorvGoyl** [comment] 2021-09-19 11:48
Yes, I'm using browser extension.

![image](https://user-images.githubusercontent.com/7106086/133926207-4992a3dd-1bdd-4227-8640-b71ffaeb8c22.png)

To reproduce this issue, You could create a local nodejs server in VSCode (I'm using [Firebase cloud functions](https://firebase.google.com/docs/functions)) and make the rest api call (`POST`) to it from Microsoft Edge browser using https://hoppscotch.io/ with it's browser extension installed.

**Comment by liyasthomas** [comment] 2021-09-19 11:51
Thanks for the detailed information. Will let you know once it's fixed. Thank you.

**Comment by mandaputtra** [comment] 2021-10-01 01:59
I can confirm that for now, this bug is resolved. I don't see any double request when I test. Using Brave Browser (with latest Chromium). It should behave the same for Microsoft Edge/Chrome since it is just chromium based browser.

![Screenshot from 2021-10-01 08-57-10](https://user-images.githubusercontent.com/23342943/135553825-4c90a4ef-033d-485f-a8e1-ef8e4a384a22.png)

![Screenshot from 2021-10-01 08-59-12](https://user-images.githubusercontent.com/23342943/135553986-73712ed1-82d0-406c-8565-298ab2314d7a.png)

**Closed** 2021-10-01 02:07 UTC
Labels: not reproducible

**Comment by mandaputtra** [comment] 2021-10-05 08:32
This actually somewhat reproducible somewhat not. Could you open this one again @liyasthomas ? I can reproduce it on my windows machine but not on my linux one. Same browser ~ in the meantime I'll figure it out why it happen.

**Comment by liyasthomas** [comment] 2021-10-05 08:40
Feel free to reopen if you can provide steps to reproduce the issue.

**Comment by long2ice** [comment] 2021-10-30 07:44
Same issue here, use chrome PWA, but everything is fine after reinstall PWA

**Comment by LaPoPvLe** [comment] 2022-03-22 05:53
same issue
in chrome, this is fine.
but pwa still send double request.like replay all request's header and content is same, not options method in cross domain.

**Comment by levrik** [comment] 2023-02-27 15:33
Having the same issue. I might have installed Hoppscotch as PWA before already but I'm not sure if it was on this exact device.
