### ISSUE TITLE
[bug]: Latest update broke bearer tokens

### ISSUE THREAD

**Issue by shynekomaid** [hoppscotch/hoppscotch#3951] opened 2024-03-29 11:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I just update hoppscotch and my API test setup dosent work 
![image](https://github.com/hoppscotch/hoppscotch/assets/34548743/a5cb9bf2-f12c-4ffb-ab84-6ff8b6b9967f)
Also, if after import collections, press F5, without saving any request, import will dismissed.

### Steps to reproduce

1. Update hoppscotch. (PWA)

### Environment

Release

### Version

Cloud

**Comment by thetronjohnson** [comment] 2024-04-01 04:35
@shynekomaid could you help us out with steps to reproduce this issue :)

**Comment by shynekomaid** [comment] 2024-04-16 11:03
@thetronjohnson I just restore 1-year old backup

**Comment by thetronjohnson** [comment] 2024-04-17 12:00
Sure, here's the corrected version:

Hi @shynekomaid, we're still not able to reproduce this issue. **If possible**, could you share the file you imported into Hoppscotch after removing all sensitive information to hello@hoppscotch.io so that we can debug this issue?

If not, would you be open to a chat with our engineering team? Please send an email to the same address so that we can set up a chat and resolve this :)

**Comment by shynekomaid** [comment] 2024-04-17 12:13
@thetronjohnson 
Thanks. I was send file

**Comment by nivedin** [comment] 2024-05-15 07:42
@shynekomaid closing the issue since our team could not reproduce the issue, please check the latest version and if the issue still persist feel to reopen.

**Closed by nivedin** 2024-05-15 07:42 UTC
Labels: bug, need testing
