### ISSUE TITLE
[bug]: Search always disabled

### ISSUE THREAD

**Issue by zachrattner** [hoppscotch/hoppscotch#3593] opened 2023-11-24 19:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The search above the collection folder always has the disabled cursor on hover and doesn't allow for text entry. This makes using Hoppscotch cumbersome on projects with 100+ collections

![Screenshot 2023-11-24 at 11 23 36 AM](https://github.com/hoppscotch/hoppscotch/assets/449150/163524e9-af08-4782-9ca1-52ff754f0eae)

This happens in both the web UI on hoppscotch.io and the Mac desktop app.

### Steps to reproduce

1. Go to any collection list
2. Try to search
3. Confirm it's always disabled

Note: it's possible the search is not always disabled, but I cannot figure out the scenarios under which it would be enabled. From my testing it always seems to be disabled. 

### Environment

Production

### Version

Cloud

**Comment by advaith-unnikrishnan** [comment] 2023-11-25 01:56
I tried to reproduce the bug in both cloud and desktop apps and the search is working fine.

**Comment by zachrattner** [comment] 2023-11-25 03:34
@advaith-unnikrishnan Can you recommend any ways to get logs or any other way to get higher fidelity information? I shared a screenshot of the search disabled but I don't know what else I can share that's helpful.

**Comment by liyasthomas** [comment] 2023-11-25 04:13
Hi @zachrattner, I believe it is a duplicate of #2097. Search on Collections under Team workspace is not supported yet. We're working on implementing this, and expect this to be released in the next major release candidate scheduled for December.

Please track the progress in previous issue ticket, hence I'm closing this issue.

**Closed by liyasthomas** 2023-11-25 04:13 UTC
Labels: bug, need testing
