### ISSUE TITLE
[feature]: request parameter description & documentation generation

### ISSUE THREAD

**Issue by piliplaker** [hoppscotch/hoppscotch#885] opened 2020-05-20 07:55 UTC
Sometimes we use postman not only for api testing , but also for documentation generation.

I know there has been a doc generator already, but it is just basicly functional, which is not enough for our daily use. We need the description per parameter and a relatively isolated page to show the doc to the guys we work with.

Also can you improve the experience  of the process when tring to generate documentation by given collection from the request page?  Now I have to copy the whole content of the collection in json form,  click the "generate documentation" button, paste the content to the box, and then finally click the generate button.

**Comment by liyasthomas** [comment] 2020-05-20 07:57
Thanks for raising concerns on current Documentation generator. Current implementation is very basic and needs major improvements. Will work on it as we move forward.

**Comment by joeetten-progenity** [comment] 2020-05-28 13:21
I agree, the documentation needs some help but it is at least semi-useful.

I'd also add that I'd expect that when I click on an object/collection in my collections tab and hit the "Generate Documentation" button, it would show me the documentation for that object/collection. 

Currently, it does not appear to do this. It just takes you to a "blank" page where you can import or paste a collection.

I can add this as a separate issue if you need.

**Comment by liyasthomas** [comment] 2020-05-28 13:27
@joeetten-progenity separate issue isn't needed - overall improvements are required which covers the mentioned use case

**Comment by perseveringman** [comment] 2020-07-15 07:04
Is anyone following up on this issue? I really want to participate in optimizing this part.😊😊😊

**Comment by liyasthomas** [comment] 2020-07-15 07:07
We're working on #955 which will introduce lot of new improvements in the core structuring. Even though this doesn't effect the Documentation part, we went quite busy with it. If you're interested to help us, do let me know. I can help.

**Comment by liyasthomas** [comment] 2020-09-08 23:46
@perseveringman shall we optimize doc generator. We could really use your help.

**Comment by perseveringman** [comment] 2020-09-09 02:39
> @perseveringman shall we optimize doc generator. We could really use your help.

Willing to help！

**Comment by liyasthomas** [comment] 2020-09-09 02:40
What features/improvements you'd like to see in current doc generator?

**Comment by perseveringman** [comment] 2020-09-09 02:50
Shall we continue the previous progress？Add the params description and optimize the layout of the document page.

**Comment by perseveringman** [comment] 2020-09-09 02:51
If you have other ideas, I am willing to help

**Comment by liyasthomas** [comment] 2020-09-09 02:55
Can start on adding param description and optimising layout as a first and will iterate then.

**Comment by perseveringman** [comment] 2020-09-09 02:59
Okay, I will resubmit a PR.

**Comment by liyasthomas** [comment] 2023-08-05 10:45
Possibly a duplicate of #2018, hence closing.

**Closed by liyasthomas** 2023-08-05 10:45 UTC
Labels: feature, help wanted
