### ISSUE TITLE
[feature]: have a tab to show current request's name and split requests

### ISSUE THREAD

**Issue by hs2222** [hoppscotch/hoppscotch#2919] opened 2023-02-06 07:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When I open a new request, I have to close the other request and I can't see current request's name

### Why should this be worked on?

Just open a new request.

**Comment by liyasthomas** [comment] 2023-02-06 07:22
We're working on improving the visibility of request's meta data and revamp REST page with tabs support. Kindly track this issue on #690. Our main focus is to improve the overall user experience and make the interface more intuitive and user-friendly.

If you have any further questions or concerns, please do not hesitate to reach out. We value your feedback and appreciate your support. Closing this issue since it's a duplicate of #690.

**Closed by liyasthomas** 2023-02-06 07:22 UTC
Labels: feature
