### ISSUE TITLE
[feature]: support pre-request-scripts for collections but each request

### ISSUE THREAD

**Issue by hhstu** [hoppscotch/hoppscotch#3884] opened 2024-03-08 08:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

support pre-request-scripts for collections but each request

### Why should this be worked on?

script work for every request in collections and sub collections

**Comment by DBJosh** [comment] 2024-03-08 12:53
Probably a duplicate of #3728

**Closed** 2024-03-11 06:09 UTC
Labels: feature
