### ISSUE TITLE
[feature]: improve usabilty of replace url parts with environment variable

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#3634] opened 2023-12-08 08:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

An internal user reported to me about problems replacing placeholders in URLs:

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/5336cdad-c245-4b2f-9b1e-c4c355d1bc63)

He already sets the placeholders with a variable name, then he chooses "set as variable"

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/81aa2c2f-412e-409a-8350-a6ca2103c0f3)

but the placeholder, which should actually be the variable name, is used as the value

Personally, I don't think this is a bug, but I think that the behavior could be improved here.

I've found that "set as variable" works not only with placeholders but generally with things that you mark. I think a more fluid behavior would be if the placeholder is used as the variable name if there are already existing placeholders, and if parts are simply marked, the value is still transferred to the value field, but then when the part is saved in the URL it is directly replaced with the variable .

### Why should this be worked on?

-

**Comment by liyasthomas** [comment] 2023-12-09 06:07
Hi @RaHehl, thanks for suggesting this improvement, it seems there's already another issue ticket which could be a duplicate of this. Please track the progress on #3489.

**Closed by liyasthomas** 2023-12-09 06:07 UTC
Labels: feature
