### ISSUE TITLE
[bug]: creating a new request 

### ISSUE THREAD

**Issue by baek-sang** [hoppscotch/hoppscotch#3518] opened 2023-11-09 07:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When creating a New Request, the header, URL, etc. of the tab currently being viewed is copied. I think it is correct that it is empty.

### Steps to reproduce

1. Add new request
2. The information in the tab you are currently viewing will be copied

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment] 2023-11-09 07:45
Possibly a duplicate of #3436.

New request save the current active tab. If you want to save a new empty request, open a new tab and save it to the collection.

**Closed by liyasthomas** 2023-11-09 07:45 UTC
Labels: bug, need testing
