### ISSUE TITLE
[bug]: Desktop app crash on startup on Windows 10

### ISSUE THREAD

**Issue by federicorosso1993** [hoppscotch/hoppscotch#3549] opened 2023-11-14 08:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I install the app and try to start it->it will crash. I can see it for a really short moment (white/black rectangle), but it will not stay for more than 1 second.
I tried on two PC already (both my work pc and my personal pc... both in italian).

### Steps to reproduce

1. Install the desktop app on Windows 10
2. Start the app

### Environment

Release

### Version

Local

**Comment by liyasthomas** [comment] 2023-11-14 08:50
This is a known issue which we're currently working on. Expect this to be solved in next stable release.

Possibly a duplicate of #3524 hence closing. Kindly subscribe to the previous issue ticket to track the progress.

**Closed** 2023-11-14 08:50 UTC
Labels: bug, need testing, desktop
