### ISSUE TITLE
Add websocket headers on initial connection

### ISSUE THREAD

**Issue by iwaduarte** [hoppscotch/hoppscotch#1619] opened 2021-04-27 15:53 UTC
**Is your feature request related to a problem? Please describe.**

The Web Socket implementation is very simple. Would be nice if I could configure the **headers** on the initial request (Upgrade) so I could use with cookies or tokens for authentication/authorization.

**Comment by liyasthomas** [comment] 2021-04-27 16:05
Let me know if these discussion threads helps you:
- https://github.com/hoppscotch/hoppscotch/issues/321#issuecomment-562377333
- https://github.com/hoppscotch/hoppscotch/issues/321#issuecomment-570662532
- https://github.com/hoppscotch/hoppscotch/issues/933#issuecomment-722711714

**Comment by iwaduarte** [comment] 2021-04-27 17:14
Unfortunately it does not. And also another user pointed that using the tricky with (username/password) does not work anymore.

For my case I work with the battle tested cookies with check on the Origin (to prevent CRSF-Cookies). Custom headers are also good. The initial connection it is HTTP so would be interesting to have.

**Comment by liyasthomas** [comment] 2021-06-15 13:45
Closing this issue on behalf of a possible duplicate of #1620.

**Closed by liyasthomas** 2021-06-15 13:45 UTC
Labels: future
