### ISSUE TITLE
[bug]: Incorrect invite link

### ISSUE THREAD

**Issue by eljump** [hoppscotch/hoppscotch#3078] opened 2023-05-24 12:10 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Hi all, i find one more bug.
When we send the invite link (from) admin to email, people get link on our main domain, but not invite link, only domain. There is no any query-params in link. 
Now i use branch release/2023.4.2 (there was fixed auth bug).

Also, if we send invite from main screen (not admin), we have a problem, that in link placed domain hoppscotch.io, but i think there should be our domain (hoppscotch-webest.ru)
### Steps to reproduce

Use release/2023.4.2 branch. All other steps from documentation.

### Environment

Release

### Version

Self-hosted

**Comment by ankitsridhar16** [comment] 2023-05-26 14:09
Hello @eljump 
If I understand correctly when you were inviting a user by email you were inviting them to join/sign-in to your infra? If this is the case then the email sent contains link where you main frontend app is running. 
For the second issue were you inviting members to join a team from the main screen ?

**Comment by sugureshs** [comment] 2023-05-26 21:46
@ankitsridhar16 I guess what @eljump is referring to is team invitation, when the user is invited to the team, an email containing a link to "Join New Team" contains hoppscotch.io as the base URL, this is because it's hardcoded [here](https://github.com/hoppscotch/hoppscotch/blob/d6c840011616317ba98f143da61b8f38bc1f5fc2/packages/hoppscotch-backend/src/team-invitation/team-invitation.service.ts#L129) in the backend,

<img width="1208" alt="Screenshot 2023-05-27 at 02 41 49" src="https://github.com/hoppscotch/hoppscotch/assets/134737239/c92bc858-8f1f-44f5-b309-88d90aab37ff">

though I have changed it to `process.env.VITE_BASE_URL`, a service side error is thrown when the invited user tries to join the team,
URL: http://localhost:3000/join-team?id=<_random_alnum_>
<img width="1208" alt="Screenshot 2023-05-27 at 02 45 24" src="https://github.com/hoppscotch/hoppscotch/assets/134737239/dd3ec5a0-29ad-4215-af09-2a28fbef29b4">

Server Log:
Error: `bug/auth/auth_no_user_ctx`
<img width="1677" alt="Screenshot 2023-05-27 at 02 33 56" src="https://github.com/hoppscotch/hoppscotch/assets/134737239/39f05283-c9f4-4f3c-8ef9-958f29b31b53">


Now, the only possible way to add the user to the team is through the admin panel.

Hoping this gets fixed soon!!

**Comment by eljump** [comment] 2023-05-29 11:06
Hello, @ankitsridhar16 
yes, you're right

if i invite from here
![image](https://github.com/hoppscotch/hoppscotch/assets/45133615/d6365001-437e-48e7-8f7a-9038f3e9b419)
I got
![image](https://github.com/hoppscotch/hoppscotch/assets/45133615/9a6fe240-442d-43d5-ac69-0d76c0eec0f2)
without any params, as i can see

If I invite from here
![image](https://github.com/hoppscotch/hoppscotch/assets/45133615/1178e927-5b57-4212-a158-6aa130e164ee)

I got link with hoppscotch.io domain
![image](https://github.com/hoppscotch/hoppscotch/assets/45133615/e2470403-da42-4d1d-adab-85d4c77da09b)

**Comment by ankitsridhar16** [comment] 2023-05-29 11:46
@eljump so the expected behaviour should have been when inviting from teams in the main screen you should have received an email invitation in the following format - `https://your-domain/join-team?id=##` am I correct ? 
You don't have an issue getting the first invitation when inviting a user through admin UI as - https://your-domain ?

**Comment by eljump** [comment] 2023-05-29 12:14
@ankitsridhar16 
Why you ask the same questions?

I signed all screenshots,
if i send invite from admin panel, the people got link with my domain, but it is no auth,
so on click they can go to my hoppscotch domain, link look like:
https://your-domain
You can see this on 1 and 2 screenshots.

If i send invite, like on 3 screenshot (from main screen), 
people got link with not my domain, but with domain, hoppscotch.io, it is on 4 screenshot.
I think, that there should be my domain, because i invite people to my team.

**Comment by eljump** [comment] 2023-05-29 12:29
@ankitsridhar16 Okey, i understand you, thanks for answers

**Comment by liyasthomas** [comment] 2023-06-04 07:56
This has been resolved in #3096.

**Closed by liyasthomas** 2023-06-04 07:56 UTC
Labels: bug, need testing, self host
