### ISSUE TITLE
[feature]: binary data header content with file upload

### ISSUE THREAD

**Issue by evbo** [hoppscotch/hoppscotch#3075] opened 2023-05-23 21:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The current feature for uploading a file works great, but some APIs require binary data in the **raw** (not form encoded)

for example, IBM's Watson API requires you pass an audio file as raw content (not a form encoded body):
```shell
curl -X POST -u "apikey:{apikey}" --header "Content-Type: audio/flac" --data-binary @audio-file.flac "{url}/v1/recognitions?callback_url=http://{user_callback_path}/job_results&user_token=job25&timestamps=true"
```

### Why should this be worked on?

While rare, headers can include file content, so a button allowing you to upload a file just like with form encoded bodies would be useful for these rare occasions.

**Comment by liyasthomas** [comment] 2023-08-26 13:25
Possibly a duplicate of #2594, hence closing.

**Closed by liyasthomas** 2023-08-26 13:25 UTC
Labels: feature
