### ISSUE TITLE
[bug]: The Windows Hoppscotch desktop app does not even open after installation.

### ISSUE THREAD

**Issue by tejeshwar-p** [hoppscotch/hoppscotch#3589] opened 2023-11-23 14:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Post installation, I just open the Hoppscotch.exe file from the installed folder and only a blank white window is shown for a second and closes automatically. Even running with administration privileges does not work.
Please check the this video for more details - [https://clipchamp.com/watch/Xpd2B14Wr7w](https://clipchamp.com/watch/Xpd2B14Wr7w)

### Steps to reproduce

1. Download Windows Hoppscotch app
2. Install in any of your installation folder
3. Open hoppscotch.exe from the installed folder
4. Program window open momentarily then closes

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment] 2023-11-23 14:17
Thanks for testing out our alpha release candidates of Hoppscotch desktop app.

This is a known issue which we're currently working on. Expect this to be solved in next stable release.

This is possibly a duplicate of #3524 hence closing. Kindly subscribe to the previous issue ticket to track the progress.

**Closed** 2023-11-23 14:17 UTC
Labels: bug, need testing, desktop
