### ISSUE TITLE
Collection level configuration  

### ISSUE THREAD

**Issue by laminekalinko2** [hoppscotch/hoppscotch#3251] opened 2023-08-09 21:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

I recently imported a postman collection where I have authorization and some request body set at the collection level, but unfortunately this feature is not supported here.
<img width="1129" alt="Screenshot 2023-08-09 at 5 05 53 PM" src="https://github.com/hoppscotch/hoppscotch/assets/13538880/ea2d24b4-0ff5-42e0-8583-ff06eae7420d">

### Why should this be worked on?

this will allow people to customise collection on workspace where different collection have different set of configuration.

**Comment by liyasthomas** [comment] 2023-08-10 01:34
Possibly a duplicate of #2259, hence closing.

**Closed by liyasthomas** 2023-08-10 01:34 UTC
Labels: feature
