### ISSUE TITLE
[bug]: Localization strings in admin dashboard

### ISSUE THREAD

**Issue by a-camacho** [hoppscotch/hoppscotch#3379] opened 2023-09-21 09:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I connect to admin dashboard, strings do not seem translated.
Even when using english language, everything works in frontend but backend shows string id's I think.

### Steps to reproduce

- Deploy Hoppscotch AIO container with external DB
- Go to admin dashboad after first login
- Seeing untranslated strings

### Environment

Production

### Version

Self-hosted
![Capture d’écran 2023-09-21 à 11 54 01](https://github.com/hoppscotch/hoppscotch/assets/29976133/7d828de5-b192-4f3e-a385-a8c1cf7220b2)

**Comment by liyasthomas** [comment] 2023-09-21 11:48
Seems like a duplicate of #3343 hence closing.
This is a known issue among a small segment of users. We're working on fixing this, please track #3343 for progress.

**Closed by liyasthomas** 2023-09-21 11:48 UTC
Labels: bug, need testing
