### ISSUE TITLE
ADA button alt desc

### ISSUE THREAD

**Issue by lewislwood** [hoppscotch/hoppscotch#3335] opened 2023-09-09 19:52 UTC
The support, workspace, login and more just say "button button" .
I tried to affix a custom label on this button , but I found out you do not even have a unque Id#.  That means when I created a lablel for 1 button, all the buttons got that label.

I know Alt descriptions can be time consuming, but a simple unique id should not be.
I was planning on doing the mod myself, but all I found was: 
packages/hoppscotch/components/button/index.ts  There did ot seem to be any code. 
This must not be react/svelt/next and am just tired so I am creating issue in hopes that someone does it.

If Hoppscotch is more accessible than Postman I will create a video to help other blind programmers.

Postman is just daunting..

**Comment by Smit1610** [comment] 2023-10-15 04:52
can please share image/video what is the issue .

**Comment by liyasthomas** [comment] 2023-10-15 11:59
Possibly a duplicate of #3334 hence closing.

We're planning to improve the accessibility of all UI components in the Hoppscotch platform. Kindly continue the conversations on #3334 to track and fix such issues.

**Closed by liyasthomas** 2023-10-15 11:59 UTC
