### ISSUE TITLE
[bug]: Unnecessary confirmation to discard current request

### ISSUE THREAD

**Issue by bfgod-rocketplays** [hoppscotch/hoppscotch#2751] opened 2022-10-07 19:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I click on a request in team collection green dot appears next to it.
If I click again - the green dot disappears.
If I click again on the same or other request - Confirmation is shown asking do I want to Save or not despite I did not done any changes at all. I can't move to another request if I press ESC, I need to press one of the two buttons.

If I did not make any changes - this popup should not appear.

### Steps to reproduce

1. Open any request in a team collection
2. Make sure there is a green dot next to it
3. Click on the same request so the green dot disappears
4. Do not make any changes on the request!!!
5. Just click on the same request again, or on another request
6. Confirmation appears

![image](https://user-images.githubusercontent.com/108836093/194641022-06f0adaf-d13a-4d53-9735-4fc09d52d34a.png)

### Environment

Production

### Version

Cloud

**Comment by mnosov622** [comment] 2022-10-07 23:35
Hello @bfgod-rocketplays !

Can you assign this issue to me, please ? I'm willing to work on it :)

**Comment by bfgod-rocketplays** [comment] 2022-10-09 20:28
@mnosov622 would love to, but I think it's up to @liyasthomas

**Comment by fehbari** [comment] 2022-10-10 00:17
Would like to confirm I'm having the same issue. It can be quite frustrating. I have to keep dismissing the dialog just navigating normally between requests.

**Comment by AndrewBastin** [comment] 2022-10-10 20:38
@mnosov622 @bfgod-rocketplays

This issue is a duplicate of #2431. Please follow the comment there for clarifications.

**Closed by AndrewBastin** 2022-10-10 20:38 UTC
Labels: bug, need testing
