### ISSUE TITLE
[bug]: Installing CLI 0.10.0 in Docker requires dependencies which are not documented

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#4227] opened 2024-07-31 12:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

For using hoppscotch cli in CI/CD pipelines in Gitlab we create a Docker image containing hoppscotch cli.

Base Image is `node:20-alpine`

Install Command is "npm install --global @hoppscotch/cli@0.10.0"

First error we got is missing pnpm:

![image](https://github.com/user-attachments/assets/bd8d0b0c-dc87-4d11-816d-79dd2f201dce)

Then tsup

![image](https://github.com/user-attachments/assets/fe7edfea-bbbb-4b58-b685-7909f8be3a05)

Then typescript:

![image](https://github.com/user-attachments/assets/8f2bd956-c5bb-4f41-96bc-68a19a00977a)

and after adding typescript we got the next errors, where we stopped trying:

![image](https://github.com/user-attachments/assets/3373ca50-5877-4155-a7f5-7d46fc3ec2d2)

In case this is not a bug, i would ask you to provide a ready to use image with CLI.

### Steps to reproduce

-

### Environment

Production

### Version

Self-hosted

**Comment by jamesgeorge007** [comment] 2024-07-31 13:30
Hi, we've identified the root cause of this issue and a fix is up #4229 on this front. It'll be addressed in a patch release for the CLI soon.

**Closed** 2024-07-31 13:40 UTC
Labels: bug, cli

**Comment by jamesgeorge007** [comment] 2024-07-31 14:02
This has been released in [Hoppscotch CLI v0.10.1](https://www.npmjs.com/package/@hoppscotch/cli). Please let us know if the issue persists.
