### ISSUE TITLE
[feature]: Allow collection requests to share the authorization method

### ISSUE THREAD

**Issue by jeliebig** [hoppscotch/hoppscotch#3477] opened 2023-10-26 10:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

This feature would allow users to configure the authorization method in the collection itself, so every request in that collection inherits it (including an already obtained token) and doesn't need to be configured again. Users are allowed to override the authentication method for every request if they wish to do so. For authorization methods like OAuth2 the collection is able to obtain and refresh the token manually and/or automatically and allows requests to use it.

Note:
The Postman importer should be able to import the authorization method for collections as well.

### Why should this be worked on?

- When working with a lot of requests in a collection it could save a lot of time, since you only need to configure authentication once. (Most of the requests likely share the same authentication method anyway.)
- Imported Postman collections would work right away (assuming you aren't using environments).
- It would be easier to change authentication across all requests of a collection in case you are testing different authentication methods

**Comment by liyasthomas** [comment] 2023-10-26 12:55
We're working on this feature, could you track its progress in #2259?

_Possibly a duplicate of #2259, so it's closing._

**Closed by liyasthomas** 2023-10-26 12:55 UTC
Labels: feature

**Comment by jeliebig** [comment] 2023-10-26 14:18
I tried multiple keyword searches and somehow still missed that issue, sorry for that!

Thank you for linking me to an existing issue!
