### ISSUE TITLE
Inconsistent network status response

### ISSUE THREAD

**Issue by duanmq1994** [hoppscotch/hoppscotch#1328] opened 2020-11-12 08:53 UTC
**Describe the bug**
I used the latest hoppscotch run the 'GET' method of self-built JIRA rest api (http://jirahost:port/rest/api/2/issue/issuename), and hoppscotch return a NETWORK ERROR response, while the actually response was 200.
I tried postman and the response was correct.

**Desktop (please complete the following information):**
 - OS: windows 7
 - Browse: chrome
 - Version: 1.9.9

**Comment by duanmq1994** [comment] 2020-11-12 09:08
I cannot attached screenshots above, so I put them in this comment.
![issue-1](https://user-images.githubusercontent.com/44471341/98919344-a5b57c80-2509-11eb-87ed-d2657d042b2e.png)
![issue-2](https://user-images.githubusercontent.com/44471341/98919372-ac43f400-2509-11eb-9084-b5ad41010029.png)

**Comment by liyasthomas** [comment] 2020-11-12 09:15
Install [Hoppscotch Browser Extension](https://github.com/hoppscotch/hoppscotch-extension) to access `localhost` and non-secured `http` endpoints.

Duplicate of #704 and #979

**Closed by liyasthomas** 2020-11-12 09:15 UTC
