### ISSUE TITLE
[bug]: Selecting a request twice from collection removes save context

### ISSUE THREAD

**Issue by vaugenwake** [hoppscotch/hoppscotch#2431] opened 2022-06-16 19:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When a user switches from one http request to another the save context is kept up to date and is switched correctly. When you select the same request again and there are no changes to the request, the save context is cleared, and selected state is removed from the request in the collection view as well as the active object is `null`.

Later if you make a change to the request you are working on and click save, you are presented with the "Save As" dialog which is incorrect. As you do not want to copy/create a new request, you want to just save the request you where already working on.

### Steps to reproduce

1. Go to collections
2. Create a new collection
3. Create 2-3 new requests and save them in your collection
4. Select a request to work on
5. Select the same request again without go to another
6. Make a change, and try to save the request

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment] 2022-06-18 08:52
This is an intended behaviour.

Clicking on the request when it is already selected dissociates the current editor save context from the request.
Clicking again brings it back to the context. We keep this for now to allow people to opt out of save contexts, in case they are playing around and don't want to accidentally modify a saved request.

I think changing the behaviour and moving the dissociation to the overflow menu or something will be a better solution. But we are starting to prioritize Tab System implementation (finally!) and we will be getting rid of this weird mechanism there by moving save context into a "Session Tab".

Hence, closing this and the associated PR as won't fix.

**Closed by AndrewBastin** 2022-06-18 08:52 UTC
Labels: bug, need testing

**Comment by vaugenwake** [comment] 2022-06-18 08:58
@AndrewBastin was not aware it was intended behavior, but thank you for clarifying.

I would support a change to this to have a more understandable user experience as many in my team & company have noted an inconsistency with saving their requests which promted the PR.

Thanks for taking the time to concider it!

**Comment by AndrewBastin** [comment] 2022-06-18 09:01
@vaugenwake thanks to you for putting in the effort to fix it! <3

As I said, we do acknowledge the issue, we are working towards implementing a Tab System which will encapsulate the "save context"-ness of open editor requests.

I can't exactly give a timeline for it, but once it is implemented, we will be able to get rid of this weird quirk once and for all.
