### ISSUE TITLE
[feature]: Allow fire other requests in pre-request scripts

### ISSUE THREAD

**Issue by xpol** [hoppscotch/hoppscotch#2177] opened 2022-03-19 01:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Allow run requests before requests.

In pre-request scripts and tests, allow invoking other requests (with their pre-script scripts and tests scripts).

### Why should this be worked on?

So that we can do complex requests flow with advanced features:

```
A -> B -> <?> -> C
           |
           +-> D -> E
```

**Comment by AndrewBastin** [comment] 2022-03-21 04:26
@xpol can you provide an example scenario where you might want a feature like this ?

**Comment by xpol** [comment] 2022-03-21 06:05
For example,
I want a login request to get the token, then call the other API like get user information.

**Comment by xpol** [comment] 2022-03-21 06:16
I know we can fire requests in the script via requests API, like in postman

```javascript
pm.sendRequest({
        url: '/api/login',
        method: 'POST',
        header: {
            'content-type': 'application/json',
            'api-key': apiKey,
        },
        body: {
            mode: 'raw',
            raw : JSON.stringify({ username, password })
        }
    }, (err, res) => {
        if (err) {
            throw err;
        }

        const auth = res.json();
        pm.collectionVariables.set('token', auth.access_token);
    });
```

 but I want to reuse existing requests managed by hoppscotch instead of writing scripts like above.

**Comment by liyasthomas** [comment] 2022-04-07 13:16
Possibly a duplicate of #2205, hence closing.

**Closed by liyasthomas** 2022-04-07 13:16 UTC
Labels: feature
