### ISSUE TITLE
[feature]: Support Generic OAuth 2.0 Authentication Provider in the Self-Hosted Version

### ISSUE THREAD

**Issue by bladeJumper** [hoppscotch/hoppscotch#3547] opened 2023-11-14 06:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add support of generic OAuth 2.0 auth allows user to setup the OAuth authentication with a complete range of providers including GitHub enterprise edition and other self-hosted OAuth services.
This can be achieved with existing library like [passport-oauth2](https://www.npmjs.com/package/passport-oauth2).
Example config:

```.env
VITE_ALLOWED_AUTH_PROVIDERS=OAUTH2

#OAuth 2.0 Auth Config
OAUTH2_AUTH_URL=https://www.example.com/oauth2/authorize
OAUTH2_TOKEN_URL=https://www.example.com/oauth2/token
OAUTH2_CLIENT_ID=*****
OAUTH2_CLIENT_SECRET=*****
OAUTH2_CALLBACK_URL=http://localhost:3170/v1/auth/github/callback
OAUTH2_SCOPE=user:email
```

### Why should this be worked on?

We are using GitHub enterprise edition instances, to leverage the authentication with that, we need to be able to configure a custom OAuth provider.
Similar functionality is supported by other application like jenkins & portainer.

**Comment by Igorgro** [comment] 2023-11-14 08:32
Duplicate of #3001

**Comment by liyasthomas** [comment] 2024-03-07 17:49
As pointed out by @Igorgro, this seems like a duplicate of #3001 hence closing.

**Closed by liyasthomas** 2024-03-07 17:49 UTC
Labels: feature
