### ISSUE TITLE
CLI throws MALFORMED_COLLECTION error when collection is exported as json 

### ISSUE THREAD

**Issue by supriyahegde** [hoppscotch/hoppscotch#4143] opened 2024-06-24 08:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I export the collection as json and try to run the collection using CLI , it throws MALFORMED_COLLECTION error.
This is observed after I upgraded Hoppscotch Desktop app to v2024.3.4
This was working fine in earlier version.

### Steps to reproduce

Export the collection to json and execute the collection json via CLI.

If we compare the collection Json files which was exported earlier with the one that is generated now after upgrade, I could see the difference as below 
Example:

New exported collection json
{"v":2,"name":"Dvha","folders":[],"requests":[{"auth":{"authType":"basic","authActive":true,"username":"<<dvh_client_id>>","password":"<<dvh_client_secret>>"},"body":{"contentType":"application/x-www-form-urlencoded","body":"\n"},"endpoint":"<<dvh_auth>>","headers":[{"active":true,"key":"Content-Type","value":"application/json"}],"method":"GET","name":"Get token","params":[],"preRequestScript":"","testScript":"\n\n// Check status code is 200\npw.test(\"Status code is 200\", ()=> {\n    pw.expect(pw.response.status).toBe(200);\n});","requestVariables":[],"v":"5"}],"headers":[],"auth":{"authType":"none","authActive":true}}

Response from CLI
MALFORMED_COLLECTION Dvha.json
Please check the collection data.

Older collection json which is working fine in CLI
{"v":2,"name":"Dvha","folders":[],"requests":[{"auth":{"authType":"basic","authActive":true,"username":"<<dvh_client_id>>","password":"<<dvh_client_secret>>"},"body":{"contentType":"application/x-www-form-urlencoded","body":"\n"},"endpoint":"<<dvh_auth>>","headers":[{"active":true,"key":"Content-Type","value":"application/json"}],"method":"GET","name":"Get token","params":[],"preRequestScript":"","testScript":"\n\n// Check status code is 200\npw.test(\"Status code is 200\", ()=> {\n    pw.expect(pw.response.status).toBe(200);\n});","requestVariables":[],"v":"4"}],"headers":[],"auth":{"authType":"none","authActive":true}}
This json runs fine in CLI
The difference is that latest one has "v":"5" as against "v":"4" in the older one

Kindly check this issue.
![Hoppscotch_json_cli](https://github.com/hoppscotch/hoppscotch/assets/7530809/cc031b80-bd7e-4e78-ab10-19e7801c4347)

### Environment

Production

### Version

Local

**Comment by jamesgeorge007** [comment] 2024-06-24 10:10
Hi, we've identified the root cause of this issue. It'll be addressed in a patch release for the CLI soon.

**Comment by jamesgeorge007** [comment] 2024-06-24 10:47
A patch release has been issued for the [CLI](https://www.npmjs.com/package/@hoppscotch/cli). Please let us know if the issue persists.

**Closed by jamesgeorge007** 2024-06-24 10:47 UTC
Labels: bug, need testing, cli
