### ISSUE TITLE
[feature]: AutoFill Query Params from url like postman

### ISSUE THREAD

**Issue by madrigal1** [hoppscotch/hoppscotch#2894] opened 2023-01-01 14:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When pasting a url with query params it auto fills the query param fields in the param tab

### Why should this be worked on?

postman has this feature

**Comment by AndrewBastin** [comment] 2023-01-06 09:56
I am not closing this issue, but we have a reason why we don't prefill the query params tab or even update the query params live unlike Postman.

See for context: https://github.com/hoppscotch/hoppscotch/pull/2857#issuecomment-1320943279

**Comment by yi-huan** [comment] 2023-03-10 03:46
I think it is possible to add a button to the right side of the request parameters to turn a request parameter into one by one, so that it does not affect the previous design

**Comment by jtleathers** [comment] 2023-05-17 23:35
#2227 Seems related and some ideas were proposed there.

**Comment by liyasthomas** [comment] 2023-09-01 13:26
Possibly a duplicate of #2227 hence closing.

**Closed by liyasthomas** 2023-09-01 13:26 UTC
Labels: feature
