### ISSUE TITLE
[bug]: Hoppscotch cli doesn't load environment variables

### ISSUE THREAD

**Issue by Blackhart** [hoppscotch/hoppscotch#2855] opened 2022-11-16 14:11 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

Given an exported environment with a "baseUrl" variable in
When I run:
`hopp test -e environment.json tests.json`
The variable "baseUrl" is not substitued in my tests.

I expect the variable "baseUrl" to be substitued

### Steps to reproduce

1. Open hopscotch
2. Open the environment panel
3. Create a new environment
4. Add 'baseUrl" as a variable of that environment
5. Create a rest request with 'baseUrl" in it
6. Export the environment and the test in json format
7. Install hopp-cli with `npm i -g @hoppscotch/cli`
8. Run them with hopp cli

### Environment

Release

### Version

Local

**Comment by Blackhart** [comment] 2022-11-16 14:33
[env_and_test_export.zip](https://github.com/hoppscotch/hoppscotch/files/10022669/env_and_test_export.zip)
![output](https://user-images.githubusercontent.com/4446461/202208353-1be3af02-b5ce-4380-9957-67fffa037c54.PNG)

**Comment by aitchnyu** [comment] 2022-12-05 07:54
The env file format is actually like this.

```
{
  "baseurl": "http://postman-echo.com"
}
```

A file of a different format would parse as a blank env. Sorry about the surprising behavior. We are fixing the code to throw an error and looking at the docs.

**Comment by aitchnyu** [comment] 2022-12-05 09:47
Updating docs at https://github.com/hoppscotch/docs/pull/96

**Comment by praveenpuglia** [comment] 2023-02-21 08:28
I feel like the cli should interactively ask for which environment I wanna run the collection with as well in case there are multiple of them. Also the format should be up-to-date with the exported format. People primarily use the GUI and then if they have to run everything in a collection together, they use the CLI. for this they export the environment variables form the GUI itself that they would have already made.

Proposal
```sh
hopp test -e env-staging.json --env-name staging collection.json
```
The `env-name` arg can then be used to pick one of the environments to work with. 

Also, there's this bit of code
```js
 if (!(contents && typeof contents === "object" && !Array.isArray(contents))) {
    throw error({ code: "MALFORMED_ENV_FILE", path, data: null });
  }
  const envPairs = [];
  for (const [key, value] of Object.entries(contents)) {
    if (typeof value !== "string") {
      throw error({ code: "MALFORMED_ENV_FILE", path, data: { value } });
    }
    envPairs.push({ key, value });
  }
```

This should be modified to work with the new data format of GUI.

**Comment by cjchand** [comment] 2023-08-07 15:12
Reiterating @praveenpuglia's point above that the CLI should support the export format from the GUI. Why would these be different? Wouldn't the GUI be the normal place people craft Collections and Environments together?

While it might seem small when viewed in isolation, this is one of a series of friction points that are driving me away from considering Hoppscotch as a Postman replacement (see also: #3248). 

That said, I am very appreciative of all the hard work on this project. It's because I see the promise that I'm providing the feedback. Thanks for the attention.

**Comment by nids2307** [comment] 2023-09-08 13:18
Any further updates on this ticket. I am in the same boat as cjchand to make a decision considering Hoppscotch as a potential replacement to Postman.

**Comment by JamesSFL** [comment] 2023-11-20 11:07
So here is what happened with me. I had  baseurl for the test endpoint set in global and rest of the variables were in development env. Since hoppscotch supports only one env file with cli, I copied the baseurl variable and pasted in development.json env file at the end of the variables array. Now when I run the the cli with this setup, the test cases failed as it wasn't able to read the baseurl which is at the bottom of the variable array. Now when I moved it to the top, all test cases passed. Is this an expected behaviour? Also cli is not able to set value for apikey in authorization as header from variable in environment file.

**Comment by jamesgeorge007** [comment] 2024-04-10 08:27
Hi, Hoppscotch CLI now supports specifying an environment export file via the `--env, -e` flag. It doesn't support the bulk environments export format. Please find more information [here](https://docs.hoppscotch.io/documentation/clients/cli).

> So here is what happened with me. I had baseurl for the test endpoint set in global and rest of the variables were in development env. Since hoppscotch supports only one env file with cli, I copied the baseurl variable and pasted in development.json env file at the end of the variables array. Now when I run the the cli with this setup, the test cases failed as it wasn't able to read the baseurl which is at the bottom of the variable array. Now when I moved it to the top, all test cases passed. Is this an expected behaviour? Also cli is not able to set value for apikey in authorization as header from variable in environment file.

@JamesSFL, can you try with the latest version of the CLI? If the issue persists, can you share a sample collection and environment export file to reproduce it?

**Comment by JoelJacobStephen** [comment] 2024-04-18 07:00
@JamesSFL I hope the suggestion helped. I will be closing this issue. If you still face this issue on the latest builds, please feel free to reopen this issue.

**Closed by JoelJacobStephen** 2024-04-18 07:00 UTC
Labels: bug, need testing, cli
