### ISSUE TITLE
[bug]: Imported Postman collections are not working

### ISSUE THREAD

**Issue by ricbermo** [hoppscotch/hoppscotch#1990] opened 2021-12-01 14:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I import a Postman collection, none of the imported requests seems to be working. After sending the request, I'm not getting responses. If I type the endpoint manually it does work.

### Steps to reproduce

1. Import a Postman collection ( you can use this one https://go.postman.co/workspace/My-Workspace~2ab78fef-e901-43a3-86bb-bb0ba130f26f/collection/5143-a7141ae8-a98a-4f65-bb47-030f4028d798)
2. try to send any of the imported requests
3. see how the the requests never ends (see the orange bar here)

![image](https://user-images.githubusercontent.com/2601363/144254186-5ce61b2e-f499-4cca-9faf-7b70b6c4c836.png)

### Environment

Release

### Version

Local

**Comment by patricksilvamor** [comment] 2021-12-02 17:04
I'm having the same issue.

**Comment by VCourdy** [comment] 2021-12-03 10:51
Same,
Here's the error when sending a request :
![image](https://user-images.githubusercontent.com/15244542/144590484-a6f68e73-da61-4bb1-aef9-2e30fdd860a4.png)

**Comment by cloudomatic** [comment] 2021-12-06 21:11
Does anyone know if this is a regression?  I have always gotten the above error on a v2.1.0 collection, but never a v1 collection.  I was interested to know if Hoppscotch was previously working with the v2 collections.

**Comment by RishabhAgarwal-2001** [comment] 2021-12-12 12:03
Hello! I was planning to work on this issue. Can I get it assigned to myself, so that I can start working?

**Comment by liyasthomas** [comment] 2021-12-12 13:30
Hi @RishabhAgarwal-2001 you can give this a try. Assigning it to you.

**Comment by JosephSanjaya** [comment] 2021-12-18 12:03
I'm also got this problem, I fix it by adding default value for param "preRequestScript", "testScript" in json that exported from imported postman json, and reimporting it. I think the problem is with that 2 param empty hoppscotch think its invalid request.

### Possible Fix
Add default empty value for "preRequestScript", "testScript" when importing from postman json.

**Comment by AndrewBastin** [comment] 2022-01-21 12:22
Hi guys,

We have pushed (https://github.com/hoppscotch/hoppscotch/commit/588d1119b5ea98e6fbe404a32330f1f4e636c598) a new importer system with revamped Postman/Insomnia/OpenAPI Spec importers.

Please have a look and see if any issues persist now.

**Closed** 2022-01-23 15:26 UTC
Labels: bug, need testing, neat for externship

**Comment by theMasix** [comment] 2022-01-24 16:24
I get this error while importing a Postman collection
<img width="632" alt="Screen Shot 2022-01-24 at 7 51 20 PM" src="https://user-images.githubusercontent.com/22872117/150822098-5f811151-507b-40e6-810e-c2733fbae6af.png">

It seems there is a file-size limitation on the server (description of 413 HTTP status code). The postman collection size is ~6MB.

I know it's not probably a bug from the client, But maybe a limitation from the server, or client should handle importing of large-size collection in another way.
.

**Comment by AndrewBastin** [comment] 2022-01-24 19:17
@theMasix can you open this as a separate issue and mention this is for Teams ? Thank you!

Also would appreciate if you could give me the count of collections/folders/requests in the Postman Collection you are trying to import.

Thanks!
