### ISSUE TITLE
[feature]: Export Collection in Postman v2.1 format 

### ISSUE THREAD

**Issue by chanminko1234** [hoppscotch/hoppscotch#3365] opened 2023-09-18 05:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Currently if we export any collection it is exported in v1 format only which is now not compatible with postman. If will be good to have export collections ax v2.1 also which will allow easily sharing

### Why should this be worked on?

v2.1 format is used widely

**Comment by liyasthomas** [comment] 2023-09-18 05:23
Duplicate of #2693 hence closing.

**Closed by liyasthomas** 2023-09-18 05:23 UTC
Labels: feature

**Comment by chanminko1234** [comment] 2023-09-18 05:24
I don't export collection import to postman format does not match

**Comment by chanminko1234** [comment] 2023-09-18 05:26
<img width="220" alt="Screenshot 2023-09-18 at 11 55 06 AM" src="https://github.com/hoppscotch/hoppscotch/assets/20737079/b2e8efb5-dd9e-41d5-9c92-21a47d7a4d95">
where export format for postman

**Comment by chanminko1234** [comment] 2023-09-18 05:26
> Duplicate of #2693 hence closing.

please help

**Comment by liyasthomas** [comment] 2023-09-18 06:09
Exporting Hoppscotch collections in Postman-supported format is not available at the moment. Please track this issue on #2693, subscribing to this issue will notify you once this feature is available.
