### ISSUE TITLE
Sending same multiple request on send

### ISSUE THREAD

**Issue by torrayne** [hoppscotch/hoppscotch#1426] opened 2021-01-12 22:22 UTC
**Describe the bug**
Every time I click send it sends 3 requests.

**To Reproduce**
Click send

**Expected behavior**
Only send one request when you click send

**Desktop (please complete the following information):**
 - OS: Pop!_OS 20.10
 - Browser Firefox
 - Version 84.0.2

**Additional context**
It's not just on my local machine. Sending request to public domains sends 3 requests.

**Comment by AndrewBastin** [comment] 2021-01-12 22:26
@djatwood Do you have the extension installed ?

**Comment by djatwood** [comment] 2021-01-12 22:54
Yes

**Comment by liyasthomas** [comment] 2021-01-12 22:55
@djatwood are you mentioning [pre-flight](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) request?

**Comment by djatwood** [comment] 2021-01-12 22:57
No, it's sending 3 full request. When testing a form it sends 3 POST requests and creates 3 submissions.

**Comment by liyasthomas** [comment] 2021-01-13 01:54
An issue has been identified with our browser extension which is making multiple requests (~3) at once. We're working on a fix. Will update ASAP.

**Comment by AndrewBastin** [comment] 2021-01-13 02:50
Umm, the fix should be live in Firefox!
Please update your extension (it should auto update tho)

And then please ping back if it persists.

**Comment by djatwood** [comment] 2021-01-13 03:09
I done a tiny bit of testing and it looks like it's fixed. I'll do some real testing tomorrow morning.

**Comment by AndrewBastin** [comment] 2021-01-14 01:38
@djatwood is it fixed ?

Closing meanwhile

**Comment by djatwood** [comment] 2021-01-14 02:08
I haven't had it happen again since the update

**Comment by njk18** [comment] 2022-11-07 12:41
I'm having the same issue, only the request is being sent 4 times.

**Desktop (please complete the following information):**

- OS: Windows 10 Version (22H2) 10.0.19045 Build 19045
- Browser: Chrome 103.0.5060.66 
- Hoppscotch Browser Extension Version: 0.25

**Comment by AndrewBastin** [comment] 2022-11-07 21:47
@njk18 can I have more details about the request ? like the HTTP method used, content type (if any), body data (just a summary of what it is enough) and stuff like that.

If you can get this from the endpoint, some details around what requests were you getting on the endpoint (like the method, data (if any) etc.) would be useful as well.

**Comment by njk18** [comment] 2022-11-08 12:50
@AndrewBastin I did a page refresh which seems to have resolved the problem.
The request used the POST HTTP method with an application/json body which consisted of only string and integer values.
The endpoint was localhost:8084.
At the time, I went back and forth resetting the database and switching between Hoppscotch and Postman to validate that the problem originated from Hoppscotch.

I'm not sure if this helps, I'll update this issue if the problem occurs again.

**Comment by SamuelJansen** [comment] 2022-11-21 02:11
> I'm having the same issue, only the request is being sent 4 times.
> 
> **Desktop:**
> 
> * OS: Windows 10 Version (22H2) 10.0.19045 Build 19045
> * Browser: Chrome 103.0.5060.66
> * Hoppscotch Browser Extension Version: 0.25

so am I

**Comment by LukeFranky** [comment] 2022-11-24 02:38
Same thing happens to me. I was getting 4 requests each time, but restarting the Chrome app brought this down to 2.

I am using the Chrome app and extension because I am testing requests to a localhost server.

I have attached a screenshot from Telerik Fiddler showing two identical requests from the same 'Send' click.

![2022-11-24 12_52_44-Hoppscotch • Open source API development ecosystem • Hoppscotch](https://user-images.githubusercontent.com/14487842/203681589-6d8bcf5c-888a-450b-bd5d-474d367462c5.png)

**Comment by ElTimuro** [comment] 2023-01-06 13:16
Same Issue, Request comes 2x. Looks like this is not fixed at lest in Chrome

OS: Windows 10 Pro
Chrome: 108.0.5359.125
Browser Extension: 0.25

**Comment by AndrewBastin** [comment] 2023-01-06 14:20
Due to the amount of reports I am reopening the issue.

For people, who are posting "Same issue" comments. Please add the following details to help out with the debugging process.

1. OS + Browser + Extension Version
2. Selected Interceptor in Hoppscotch
3. Some details about the repeated network call (if possible), things like: HTTP Method, URL (you can hide your domain or other private info, I only want to see if there are any differences) and Body (if any, again, this can be private, I just want any notes in any differences between the bodies in the multiple calls).

**Comment by hms5232** [comment] 2023-02-03 08:16
One click, two request. 

* OS: Windows 10 64bit
* Browser: Chrome 109.0.5414.120 64bit
* Extension: 0.25

![圖片](https://user-images.githubusercontent.com/43672033/216546353-058048d6-4b3a-4668-a3e8-90fd9f3cd46a.png)

I use to develop API, request localhost server. The POST method requests has bearer token in header, JSON body like:

```json
{
  "image_id": 42,
  "link": "https://whl4u.jp/",
  "target": "__blank"
}
```

**Comment by hms5232** [comment] 2023-02-06 07:56
> One click, two request.
> 
>     * OS: Windows 10 64bit
> 
>     * Browser: Chrome 109.0.5414.120 64bit
> 
>     * Extension: 0.25
> 

After restarting, it seems good and work fine again. 😕 Maybe something went wrong during updating from old version.

**Comment by ItsEthra** [comment] 2023-03-01 12:23
Any updates on it? I am experiencing the same issue.
* Os: Arch linux, lts kernel.
* Browser: Firefox 110.
* Extension version: 0.25
Happens with GET, POST requests, could be others as well I have not checked though.

**Comment by ugudango** [comment] 2023-03-21 11:36
I tried restarting, this issue keeps occurring.

Well, at least it's motivating me to do some implement some idempotency in my system, I guess.

**Comment by RVFET** [comment] 2023-04-02 12:32
Using Chrome Web App on Win11, Browser Extension installed (otherwise localhost server don't work somehow) and facing the same issue, each request gets sent thrice. It's very annoying as my app does some scraping when receiving certain "POST" request and app forcibly overloads the api. This is my all time fav API testing client, please update it if possible. Thank you for all your effort!

**Comment by sons-of-titus** [comment] 2023-05-12 13:53
Same thing with LibreWorlf(firefox) extension on archlinux.
1 click 3 requests

**Comment by catch-songcs** [comment] 2023-07-10 08:12
this issue keeps occurring
but it fixed when I restart application

- OS: macOS Ventura(13.4.1)
- Browser: Chrome(114.0.5735.198)
- Extension: 0.25

**Comment by lcdss** [comment] 2023-07-13 19:17
Same here on firefox and latest version of everything; every request is made twice, but after restarting the browser it back to work as expected.

**Comment by cabralski** [comment] 2023-08-24 19:12
I am having the same problem, sometimes it sends exactly three times. When it happens, I <kbd>SHIFT</kbd> + <kbd>F5</kbd>, and it stops sending the POST requests thrice.

**Comment by Tiller** [comment] 2023-08-29 06:55
Hoppscrotch 2023.4.8 installed as PWA on Chromium 116.0.5845.110 running on Ubuntu 22.04.
With browser extension 0.25 enabled, a single click to my POST query leads to 2 calls :
![image](https://github.com/hoppscotch/hoppscotch/assets/831119/c9b68068-5abf-4538-8669-bb2a173a6deb)

Not gonna lie, that's kind of a deal breaker for me... especially when the issue is 2+ years old...

**Comment by Spotnyk** [comment] 2023-11-02 19:12
I just spent two hours trying to debug why my code was doing this; eventually narrowing it down to hopscotch.

Three things:
1. Force quitting and restarting the app resolved it.
2. I've only had hoppscotch for about a month, so this is a new install.
3. It's likely been open for a week straight when this happened.

OS: Windows 11 64bit
Interceptor: Chrome v0.25 / (Chrome 118.0.5993.118)
Method: `POST`
URL: `https://partner-dev-spot.domain.com/ingest/<<spotAuthHash>>`
Headers: `application/json`
Payload:
```json
{
  "rawId": "rpl-usf-27efcf83-1f5e",
  "orderNumber": "BF46305",
  "orderUniqueId": "BF46305111",
  "shopifyShopId": 123123123123,
  "email": "person@gmail.com",
  "reference": "This is a reference string",
  "items": [
    "9991",
    "9992",
    "9993",
    "9994",
    "9995",
    "9996",
    "9997"
  ]
}
```

(_not_ the cleanest setup, but the requesting source is archaic; requiring some odd choices 😅 )

**Comment by Wurstnase** [comment] 2023-11-03 11:06
I can see this issue also with OAuth 2.0 -> Generate Token.

**Comment by kiranmurali93** [comment] 2023-11-06 10:35
Having the same issue

OS: Mac OS 14 
Browser: Firefox
Extension Version: 0.25


For me its sending 2 request irrespective of the method of the request.

**Comment by prom00** [comment] 2023-11-10 07:36
I'm getting 2 requests server side too. Only 1 in the hoppscotch history tab.
While debugging, the complete request is incoming twice on our REST NestJS server.

OS: Windows 11 Pro  Version: 10.0.22621 Build 22621
Browser Chrome Version: 119.0.6045.106 
Extension version: 0.25

The `CTRL + SHIFT + R` from @cabralski fixed my issues too. 
I've tried to get double requests again, but can't seem to reproduce it yet.

**Comment by cabralski** [comment] 2023-11-11 16:13
This problem, sadly, had to made me stop using Hoppscotch and use another HTTP client instead. 😓

**Comment by prom00** [comment] 2023-11-13 06:49
And today we have the same issue. Looks like it happens due to the origin being "gone" from the hoppscotch chrome plugin:
![image](https://github.com/hoppscotch/hoppscotch/assets/46184489/45b00608-5dfa-458a-8b41-8060a3e6cb4b)

Our remote origin was missing again this morning. I then readded it. Now when I do requests, I get 2 requests again.

We have the directory where hoppscotch is hosted secured with basic folder authentication, to prevent everyone from registering or seeing our data.

**Comment by dakujem** [comment] 2024-01-10 15:34
Interesting... this was happening to me too in Firefox/Windows. I got here while searching. 

The issue is gone after hard-reloading the site. 🤷‍♂️

**Comment by david1542** [comment] 2024-01-10 23:00
This happens to me to :( It sends 2 requests when I send POST requests.

**Comment by kdomic** [comment] 2024-01-12 10:25
Do we know how to fix this? We have the same problem. Most of the time everything works fine, but at some random points it starts sending 2/3/4 requests on one call. If someone has a suggestion on how to fix this, we need it as soon as possible. Thanks.

**Comment by liyasthomas** [comment] 2024-01-12 10:58
@kdomic as per this comment: https://github.com/hoppscotch/hoppscotch/issues/1426#issuecomment-1885086889, can you try reloading and see if the issue persists?

**Comment by prom00** [comment] 2024-01-12 11:55
> @kdomic as per this comment: [#1426 (comment)](https://github.com/hoppscotch/hoppscotch/issues/1426#issuecomment-1885086889), can you try reloading and see if the issue persists?

The reload is only a temporary fix and needs to be done everytime the issue occurs again.

**Comment by kdomic** [comment] 2024-01-15 14:37
Unfortunately reload did not help. But if it did, that is not a fix for this problem. That is just a temporary solution. We need a fix so that we don't get this error randomly. After some time this problem disappears so that we can use HS right now. But at any point this can be a problem again.

**Comment by 928597712** [comment] 2024-01-23 09:08
I found a very strange way to reproduce it.Using Chrome (it does not reproduce with Edge, I haven't tried with Firefox), adding the URL to the "bookmark bar" (it doesn't reproduce when added to "bookmarks"), and then clicking the added bookmark to enter the website, clicking "send" will trigger this issue.If you refresh the website with F5 midway, it will return to normal. The issue only occurs when entering the website through the bookmark bar.

**Closed** 2024-01-31 13:25 UTC
Labels: bug
