### ISSUE TITLE
[feature]: Collection-wide environment headers

### ISSUE THREAD

**Issue by sungvzer** [hoppscotch/hoppscotch#2869] opened 2022-12-05 14:47 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Summary

Like Postman, it'd be great if we could set headers to be used collection-wide (e.g. for Access Tokens).

### Why should this be worked on?

This could save quite a few headaches when actively developing an API; imagine spending half an hour to debug something only to then discover you forgot to add the appropriate header to the request.
For example by setting a collection wide `Authorization` header, every request could be authenticated.
Post-request scripts could also be used to set this header :D

**Comment by liyasthomas** [comment] 2023-10-26 12:53
We're working on this feature, could you track its progress in #1741?

_Possibly a duplicate of #1741, so it's closing._

**Closed by liyasthomas** 2023-10-26 12:53 UTC
Labels: feature, sandbox
