### ISSUE TITLE
[bug]: Selfhosted Generate Code ist Broken

### ISSUE THREAD

**Issue by RaHehl** [hoppscotch/hoppscotch#4008] opened 2024-04-25 07:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i select generate code to see the request including headers that should be send it shows an error message "something went wrong" 

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/f290a091-7488-4a1b-b34b-e8f40fec7638)

and i get this in the browser console:

![image](https://github.com/hoppscotch/hoppscotch/assets/7577984/7f7d8677-692c-4999-a123-c13919ea58f6)

we are using 2024.3.1 selfhosted

### Steps to reproduce

Click generate Code and you get the error

### Environment

Production

### Version

Self-hosted

**Comment by amk-dev** [comment] 2024-04-25 14:00
Hey can you give me a sample request to reproduce this behaviour. you can use hoppscotch export to get the request. usually errors like this can happen due to invalid data, can you check if your headers/json request contains any malformed data.

**Comment by RaHehl** [comment] 2024-04-25 14:08
@amk-dev this happens in my case even with https://echo.hoppscotch.io in incognito mode without login

**Comment by liyasthomas** [comment] 2024-05-11 07:18
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Closed by liyasthomas** 2024-05-11 07:18 UTC
Labels: bug, need testing
