### ISSUE TITLE
[feature]: 

### ISSUE THREAD

**Issue by stevelix** [hoppscotch/hoppscotch#3218] opened 2023-07-27 22:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Could we have an up to date docker image https://hub.docker.com/r/hoppscotch/hoppscotch? The latest one is 5 months ago. 

### Why should this be worked on?

It will be easier to use in cloud.

**Comment by webysther** [comment] 2023-07-30 15:44
Not a official one, only in few months, you can use this one is update: https://hub.docker.com/r/webysther/hoppscotch

**Comment by liyasthomas** [comment] 2023-08-04 06:49
Possibly a duplicate of #3069, hence closing.

**Closed by liyasthomas** 2023-08-04 06:49 UTC
Labels: feature, self host
