### ISSUE TITLE
[feature] import and show code should be in a separate dropdown

### ISSUE THREAD

**Issue by tkp-richard** [hoppscotch/hoppscotch#2233] opened 2022-04-04 05:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Import cURL and show code has no relation to "send". It would make more sense if they were put under a separate dropdown. Additionally, the documentation no longer reflects the current UI
https://github.com/hoppscotch/hoppscotch/wiki/Import-cURL

![image](https://user-images.githubusercontent.com/83326962/161478406-d877cb99-fd1a-4e01-9433-4db368877f08.png)

### Why should this be worked on?

see above.

**Comment by Wils3B** [comment] 2022-04-05 22:33
I agree with you, from my point of view, these buttons are not very intuitive when they are put at this place

I suggest moving the import code to the space between the method selection and the URL entry.
The display code can be moved to the right aside split panes as described in the following image:

![hoppscotch-feature-proposition](https://user-images.githubusercontent.com/44102335/161861767-85ab49fe-1c1e-42c2-8740-99b40611efde.png)

**Comment by jaysoni-ash42** [comment] 2023-04-19 11:45
@liyasthomas  @abraham  created a branch for this proposed ui/ux feature change. is there any further change on the design language?

**Comment by hartmark** [comment] 2024-10-11 10:34
The workaround of just having the "Code snippet" to show the actual request doesn't seem to include Authorization header included from the collection.

As you can see here the Headers contain the Authorization header that is masked but in the generated code there's no Authorization header added.

![image](https://github.com/user-attachments/assets/e3854466-266d-478e-a822-561a4e7ee2df)

**Comment by liyasthomas** [comment] 2024-10-11 10:41
Hey @hartmark, I can't reproduce this behavior at my end. Can you let me know which authentication method are you using?

**Comment by hartmark** [comment] 2024-10-11 10:50
I was using the windows client and bearer token

**Comment by liyasthomas** [comment] 2024-11-08 13:10
Thank you, @raoulkent, for the bug report, we'll look into it shortly.

**Comment by liyasthomas** [comment] 2024-11-08 13:11
Closing this ticket as this particular feature request is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Closed by liyasthomas** 2024-11-08 13:11 UTC
Labels: feature
