### ISSUE TITLE
pnpm run generate -  failing on Ubuntu 

### ISSUE THREAD

**Issue by kani** [hoppscotch/hoppscotch#1843] opened 2021-10-01 02:50 UTC
Thank you for this wonderful project, wanted to try this while we wait for the teams feature. We are planning to host our own version for our team.

Following the steps on this section: https://github.com/hoppscotch/hoppscotch#releasing

Getting this error, please help. Tried this using sudo and non root user on Ubuntu 16.04

node: v16.10.0
npm: 7.24.0 

ubuntu@host:~/hoppscotch$ sudo pnpm run generate

> hoppscotch-app@2.0.0 generate /home/ubuntu/hoppscotch
> pnpm -r do-build-prod

Scope: all 3 workspace projects
packages/hoppscotch-js-sandbox do-build-prod$ pnpm run build
│ > @hoppscotch/js-sandbox@1.0.0 build /home/ubuntu/hoppscotch/packages/hoppscotch-js-sandbox
│ > npx tsc
└─ Done in 8.6s
packages/hoppscotch-app do-build-prod$ pnpm run generate
│ > hoppscotch-app@2.0.0 generate /home/ubuntu/hoppscotch/packages/hoppscotch-app
│ > nuxt generate --modern
│ ℹ windicss@3.1.7 running with config: windi.config.js
│  WARN  Modules should be only specified once: unplugin-vue2-script-setup/nuxt
│ Killed
│  ELIFECYCLE  Command failed with exit code 137.
└─ Failed in 8m 21.2s
/home/ubuntu/hoppscotch/packages/hoppscotch-app:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  hoppscotch-app@2.0.0 do-build-prod: `pnpm run generate`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by liyasthomas** [comment] 2021-10-01 03:01
Hi @kani, I can't reproduce this issue at my end. Make sure you have the latest version of NodeJS (>=v14) installed and proper environment variables defined while building the project for release.

You can find the default list of environment variables in `.env.sample` under `packages/hoppscotch/`.

**Comment by kani** [comment] 2021-10-02 04:18
@liyasthomas  Thank you!!!

It is working now!

Is there any way to disable the Login using Github option on the site?
Looking forward to see the team feature in action! Thank you for actively supporting this project. 

I did the following to get this working.

1. Switched to Ubuntu 20, earlier I was trying to run the release commands on Ubuntu 16.
2. Installed the latest node, nodejs, npm
3. Created a firebase project, Spark free plan (https://console.firebase.google.com/) and copied those configurations (Project settings > add webapp) to .env under (packages/hoppscotch-app)
 - Under firebase project > Authentication 
 * Added the authorized domains (the domain hosting the static files)
 * Enabled the sign-in providers (Email/Password, Gmail) I did not enable Github as we are not going to use that provider. 
4. Followed the steps here: https://github.com/hoppscotch/hoppscotch#releasing
5. Got the static files under packages/hoppscotch-app/dist
6. Configured an Apache virtual host specifically for hosting this as the index.html expecting the files in the root directory (ex: src="/_nuxt/2cc3608.modern.js") 
7. Copied the static files from dist folder to the root folder of the new virtual host. 

navigating to https://[domain.com] loads this awesome tool!

$ pnpm run generate
[212 lines collapsed]
│ ✔ Generated route "/vi/documentation"
│ ✔ Generated route "/vi/enter"
│ ✔ Generated route "/vi/graphql"
│ ✔ Generated route "/vi/home"
│ ✔ Generated route "/vi/realtime"
│ ✔ Generated route "/vi/settings"
│ ✔ Generated route "/"
│ ✔ Client-side fallback created: 404.html
│ ℹ Generating sitemaps
│ ✔ Generated /sitemap.xml
└─ Done in 15.4s

**Comment by liyasthomas** [comment] 2021-10-02 04:32
@kani, glad it worked out for you.
We're working on an in-built self-hostable instance of Hoppscotch for next major product release milestone. This will allow users to configure auth, database and backend providers as per their choice and is configurable. Thanks for your patience, watch the project on GitHub for upcoming updates.

Closing this issue.

**Closed by liyasthomas** 2021-10-02 04:32 UTC
Labels: need testing, need information

**Comment by leandro-toledo-uux** [comment] 2022-01-07 20:15
> @liyasthomas Thank you!!!
> 
> It is working now!
> 
> Is there any way to disable the Login using Github option on the site? Looking forward to see the team feature in action! Thank you for actively supporting this project.
> 
> I did the following to get this working.
> 
> 1. Switched to Ubuntu 20, earlier I was trying to run the release commands on Ubuntu 16.
> 2. Installed the latest node, nodejs, npm
> 3. Created a firebase project, Spark free plan (https://console.firebase.google.com/) and copied those configurations (Project settings > add webapp) to .env under (packages/hoppscotch-app)
> 
> * Under firebase project > Authentication
> 
> * Added the authorized domains (the domain hosting the static files)
> * Enabled the sign-in providers (Email/Password, Gmail) I did not enable Github as we are not going to use that provider.
> 
> 4. Followed the steps here: https://github.com/hoppscotch/hoppscotch#releasing
> 5. Got the static files under packages/hoppscotch-app/dist
> 6. Configured an Apache virtual host specifically for hosting this as the index.html expecting the files in the root directory (ex: src="/_nuxt/2cc3608.modern.js")
> 7. Copied the static files from dist folder to the root folder of the new virtual host.
> 
> navigating to https://[domain.com] loads this awesome tool!
> 
> $ pnpm run generate [212 lines collapsed] │ ✔ Generated route "/vi/documentation" │ ✔ Generated route "/vi/enter" │ ✔ Generated route "/vi/graphql" │ ✔ Generated route "/vi/home" │ ✔ Generated route "/vi/realtime" │ ✔ Generated route "/vi/settings" │ ✔ Generated route "/" │ ✔ Client-side fallback created: 404.html │ ℹ Generating sitemaps │ ✔ Generated /sitemap.xml └─ Done in 15.4s

Hi @kani , there is something not clear to me yet... are you hosting only the files generated in "dist" directory? I mean, did you get the files from /dist and moved to another directory (the one which apache point to)? What about firebase configuration? I mean, it is not in the dist folder, how it is supposed to work since it is only serving static files...  thanks

**Comment by kani** [comment] 2022-01-08 05:36
@leandro-toledo-uux  


You can follow the steps here for hosting your own version,
https://github.com/hoppscotch/hoppscotch/wiki/Hosting

Update .env.example file found in packages/hoppscotch-app with your own keys and rename it to .env.

Here is the contents of my folder if that helps.

![image](https://user-images.githubusercontent.com/163713/148632940-a2e17889-f3a7-4774-95d6-473073881d22.png)


I tried it for checking the teams features, not using it now as the teams features is not available for selfhosted version.
