### ISSUE TITLE
Add import option of OpenAPI json/yaml

### ISSUE THREAD

**Issue by mnixry** [hoppscotch/hoppscotch#1406] opened 2021-01-01 10:33 UTC
**Is your feature request related to a problem? Please describe.**
Some framework such as `fastapi` generated a `openapi.json`. I want to import this easily to hoppscotch

**Describe the solution you'd like**
Add a option to make import OpenAPI file possible

**Additional context**
related with #1182

**Comment by liyasthomas** [comment] 2021-01-01 10:37
Duplicate of #1182 hence closing.
Don't create duplicates of existing feature request.

**Closed by liyasthomas** 2021-01-01 10:37 UTC
Labels: duplicate
