### ISSUE TITLE
[feature]: Import environment from Postman

### ISSUE THREAD

**Issue by ngocthua830** [hoppscotch/hoppscotch#2491] opened 2022-07-04 03:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

When import collection that using variables from Postman to Hoppscotch, all request are imported but not variables. I have to create environment manually.

### Why should this be worked on?

That would be great if Hoppscotch have feature import environment's variable from Postman.

**Comment by liyasthomas** [comment] 2022-07-04 12:20
Possibly a duplicate of #2124. Hence closing.

**Closed by liyasthomas** 2022-07-04 12:20 UTC
Labels: feature

**Comment by KartikSoneji** [comment] 2022-07-07 16:26
Hi @ngocthua830 
Can you please provide a sample postman collection to demonstrate the issue?

**Comment by ngocthua830** [comment] 2022-07-08 02:19
Hi @KartikSoneji I used this sample json file for import to hoppscotch, all item are imported but variables.
`{
	"info": {
		"_postman_id": "cf08d0bd-8b31-4748-bf7e-f059de976e6c",
		"name": "sample_collection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "sample_post",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "binary_file",
							"type": "file",
							"src": "/home/thua/Downloads/avatar.jpeg"
						},
						{
							"key": "age",
							"value": "23",
							"type": "text"
						}
					]
				},
				"url": {
					"raw": "{{domain}}/upload",
					"host": [
						"{{domain}}"
					],
					"path": [
						"upload"
					]
				}
			},
			"response": []
		}
	],
	"auth": {
		"type": "bearer",
		"bearer": [
			{
				"key": "token",
				"value": "this_is_token",
				"type": "string"
			}
		]
	},
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "domain",
			"value": "https://sample.com/"
		},
		{
			"key": "sample_name",
			"value": "sample1"
		}
	]
}`
