### ISSUE TITLE
Teams Not Working After Connecting own firebase creds

### ISSUE THREAD

**Issue by shuklaharshit** [hoppscotch/hoppscotch#2875] opened 2022-12-10 08:04 UTC
```
{
    "errors": [
        {
            "message": "auth/fail",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "createTeam"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR"
            }
        }
    ],
    "data": null
}
```
The above code is the response of the network when I am trying to create teams.

Showing "loading..." continuously in teams and "something went wrong"
please help me out.

I am unsure whether I must deploy some post API of graphql or what ??

**Comment by AndrewBastin** [comment] 2022-12-11 02:09
Duplicate of #2808

**Closed by AndrewBastin** 2022-12-11 02:09 UTC
