### ISSUE TITLE
[feature]: individual environment file export

### ISSUE THREAD

**Issue by nids2307** [hoppscotch/hoppscotch#3292] opened 2023-08-24 22:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

The import/export of environment file is not available at the individual environment file level. It is only available to export all the environment files including variables from those multiple files.

![env file export](https://github.com/hoppscotch/hoppscotch/assets/57542472/a90ba6d1-6660-4f1b-9ee9-1a7fd9afa534)

### Why should this be worked on?

I have multiple collections in the workspace each using a different environment file. I need to run specific collection in the CLI using a particular environment file json.

Currently the tool does not provide an option to export individual environment file and is only available at the top level which exports all the environment files in a single json.

**Comment by liyasthomas** [comment] 2023-08-26 13:32
Possibly a duplicate of #3248, hence closing.

**Closed by liyasthomas** 2023-08-26 13:32 UTC
Labels: feature
