### ISSUE TITLE
[feature]: Add notes @ request/collection level

### ISSUE THREAD

**Issue by golavr** [hoppscotch/hoppscotch#2247] opened 2022-04-09 02:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Add a new notes tab so users can write some notes about requests. 
It can be a plain simple one in phase 1 afterward it can be rich text supporting links and other enhancements.

### Why should this be worked on?

Some APIs calls have multiple parameters w/ multiple options. 
Giving the ability to attach/copy the documentation or placing a link to documentation will make the user's life much easier.
The size can be limited so users won't abuse the feature.

Postman has this feature...

![image](https://user-images.githubusercontent.com/22896741/162553280-0cca9721-4d6b-4515-a5bd-c5f8752fbd9b.png)

**Comment by GiorgioBertolotti** [comment] 2022-05-10 07:26
I'd love to see this too, it could be very meaningful for requests where you have optional parameters, different kind of responses and you want to share this informations with all the team.

**Comment by azvyae** [comment] 2023-07-12 00:07
I just made an [postman api v2.1 parser ](https://github.com/azvyae/dokunext) but that built with react. Maybe i could help you guys here to create pull request to develop this feature, i guess it should be straightforward to develop this. Before that has anyone attempt to built this for hoppscotch?

**Comment by liyasthomas** [comment] 2023-08-05 10:45
Possibly a duplicate of #2018, hence closing.

**Closed by liyasthomas** 2023-08-05 10:45 UTC
Labels: feature
