### ISSUE TITLE
[bug]: PWA Cache

### ISSUE THREAD

**Issue by Tarrowren** [hoppscotch/hoppscotch#2369] opened 2022-05-27 03:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

First of all, I appreciate the developer's work, the website features are updated very fast. However, the page does not display properly after each update, I need to manually clear the browser cache and then refresh the page (**every time I lose the configuration and history data :(** 
I took a brief look and found that some js files were not cached:

![image](https://user-images.githubusercontent.com/35626141/170623915-e6bb783e-f285-4c4f-ab51-2b763bfaeb03.png)

### Steps to reproduce

1. Waiting for update
2. Open website

### Environment

Production

### Version

Cloud

**Comment by AndrewBastin** [comment] 2022-05-27 09:22
@Tarrowren thank you for your kind words 😊 

But, I am a bit confused, I am not able to reproduce this and moreover, during an update of course a lot of the JS files will be invalidated, but the browser should be cleanly able to fetch in the new version and load it in. Are you offline or have some difficulties like that ?

Which browser are you using specifically ? Do you have any security features enabled which maybe of concern ?

**Comment by Tarrowren** [comment] 2022-05-27 11:23
Does the cache require workbox.js to work properly? I currently can't access cdn.jsdelivr.net

**Comment by AndrewBastin** [comment] 2022-05-31 12:09
@Tarrowren Yes, we use workbox for it and that needs to be accessible, I will keep the issue open for potential solutions and ways to get around that.

**Closed** 2023-08-01 01:25 UTC
Labels: bug, need testing
