### ISSUE TITLE
[bug]: Cannot change user name in profile

### ISSUE THREAD

**Issue by a-camacho** [hoppscotch/hoppscotch#3521] opened 2023-11-09 08:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to change my user (admin or not) from profile page, app says that name has been edited correctly and saved.
When checking in admin dashboard or in profile page, user stays Unamed.
I am not able to change user name even on Admin dashboard.
I tried to change an admin user name, and also a normal user name.

### Steps to reproduce

1. Install Hoppscotch
2. Fix SMTP with fix from Github
3. Create users
4. Try to change username from profile or admin dashboard

### Environment

Production

### Version

Self-hosted

**Comment by prom00** [comment] 2023-11-14 08:51
We have the same issue, we now changed the names via the database.

**Comment by JamesSFL** [comment] 2023-11-16 08:57
Same issue here. Also got the admin privilege issue on my first user login (did not gain admin rights somehow). I had to update via database.

**Comment by liyasthomas** [comment] 2023-11-16 09:44
@balub @amk-dev can you look into this?

**Comment by mstimvol** [comment] 2024-01-08 17:42
Still having the same issue with the latest version.

**Comment by brhahlen** [comment] 2024-01-17 13:01
Same issue here

**Comment by jobartim44** [comment] 2024-02-15 09:32
The problem still exist with 2023.12.4

**Comment by jobartim44** [comment] 2024-02-27 18:05
COUld it be in the 2024.3.0 ?

**Comment by JoelJacobStephen** [comment] 2024-04-18 06:46
@a-camacho I am unable to reproduce this issue in the latest builds. Also you can now change the name from the Admin Dashboard as well. Hence, I will be closing this issue in a few days. If you are still facing this issue in the latest builds, please let us know.

**Closed** 2024-04-29 12:26 UTC
Labels: bug, need testing, self-host
