### ISSUE TITLE
[bug]: hoppscotch returns 404 instead of 301

### ISSUE THREAD

**Issue by yvz5** [hoppscotch/hoppscotch#3698] opened 2023-12-27 08:35 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to test an endpoint which returns 301, hoppscotch returns 404 instead of the actual response code 301

### Steps to reproduce

1. have an endpoint which return 301
2. add a request pointing to that  endpoint
3. watch hoppscotch return 404 instead of 301

### Environment

Production

### Version

Local

**Comment by liyasthomas** [comment] 2023-12-27 13:02
Hoppscotch automatically follows redirects, hence [301 Moved Permanently](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) will fetch redirected URL and show its response which might result in [404 Not Found](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) if that resource is not found.

Since this is an expected behavior, I'll close this issue ticket.

To track progress on automatically following redirects check #2095.

**Closed by liyasthomas** 2023-12-27 13:02 UTC
Labels: bug, need testing
