### ISSUE TITLE
[bug]: 503 Service Unavailable error for hoppscotch-websocket.herokuapp.com

### ISSUE THREAD

**Issue by bartolomej** [hoppscotch/hoppscotch#2064] opened 2022-01-15 20:30 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When I open https://hoppscotch.io/realtime subpage to play around with websockets I get the bellow error in logs:

![Screenshot 2022-01-15 at 21 29 12](https://user-images.githubusercontent.com/36109955/149636778-7de2ef67-61ff-473d-94f1-8a22d996996b.png)

Turns out the websockets server is down: https://hoppscotch-websocket.herokuapp.com (i get 503 http error).

### Steps to reproduce

1. Go to https://hoppscotch.io/realtime
2. Check the logs

### Environment

Production

### Version

Cloud

**Comment by liyasthomas** [comment] 2022-01-17 03:56
Possible duplicate of #2049.

https://github.com/hoppscotch/hoppscotch/issues/2049#issuecomment-1003496894

**Closed by liyasthomas** 2022-01-17 03:56 UTC
Labels: bug, need testing
