### ISSUE TITLE
CI feature: integrate pull request preview environments

### ISSUE THREAD

**Issue by waveywaves** [hoppscotch/hoppscotch#2905] opened 2023-01-24 11:30 UTC
I would like to support Hoppscotch by implementing [Uffizzi](https://github.com/UffizziCloud/uffizzi) preview environments.
Disclaimer: I work on [Uffizzi](https://github.com/UffizziCloud/uffizzi).

Uffizzi is a Open Source full stack previews engine and our platform is available completely free for Hoppscotch (and all open source projects). This will provide maintainers with preview environments of every PR in the cloud, which enables faster iterations and reduces time to merge. You can see the open source repos which are currently using Uffizzi over [here](https://uffizzi.notion.site/)

Uffizzi is purpose-built for the task of previewing PRs and it integrates with your workflow to deploy preview environments in the background without any manual steps for maintainers or contributors.

We can go ahead and create an Initial PoC for you right away if you think there is value in this proposal.

**Comment by liyasthomas** [comment] 2023-01-24 11:39
Possible duplicate of https://github.com/hoppscotch/hoppscotch/pull/2627#issuecomment-1232908196, hence closing.

**Closed by liyasthomas** 2023-01-24 11:39 UTC
