### ISSUE TITLE
[bug]: I can't export a collection or environment - Desktop Mac

### ISSUE THREAD

**Issue by BAY-EJQMB** [hoppscotch/hoppscotch#4332] opened 2024-09-08 16:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Using version 24.8.1-0 (20240901.181316).

I'm trying to export a collection via JSON. When I click the option "Export as JSON", it displays the message "Download started" but nothing happens after that. 

Is the file saved in a specific directory that I can search for?

### Steps to reproduce
1. I'm not logged
1. I go to the folder icon with a down arrow
1. I click on the "Export as JSON" option
1. The message "Download started" is displayed

### Environment

Production

### Version

Local

**Comment by jamesgeorge007** [comment] 2024-09-09 09:17
Hi, thanks for reporting. We've identified the root cause of this issue and a [fix](https://github.com/hoppscotch/hoppscotch/pull/4336) is up. This will be resolved in the next patch release.

**Comment by jamesgeorge007** [comment] 2024-09-12 08:33
The fix is now released with [v2024.8.2](https://github.com/hoppscotch/hoppscotch/releases/tag/2024.8.2).

**Closed by jamesgeorge007** 2024-09-12 08:33 UTC
Labels: bug, need testing, desktop
