### ISSUE TITLE
Control arrow right and left still bind to change history

### ISSUE THREAD

**Issue by mandaputtra** [hoppscotch/hoppscotch#1840] opened 2021-09-27 04:12 UTC
**Describe the bug**
Mostly when I navigate the text, I use `CTRL + <-` or `CTRL + ->` to navigate per word, but when I use it on the body editor it navigate through my browser history not per word.

**To Reproduce**
1. Open Hoppsctoot
2. Go to body 
3. Change content type to application/json, 
4. Write stuff,
5. Navigate using CTRL + Right  or CTRL + Left

**Expected behavior**
Navigating per word

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Browser: Brave latest, Chromium (94) latest.
 - Version  V1.29.81 (Sep 14, 2021)

**Additional context**
I thik I can contribute to solve this issue. Tell me If this is necessary I'll work on it.

**Comment by liyasthomas** [comment] 2021-09-27 04:27
hi @mandaputtra, thanks for reporting this behavior. We'd be happy if you can figure out a fix to this.

I'd like to mention our universal action handler and resolver logic which is probably the root cause of this behavior.

`actions.ts` defines the key bindings and it's corresponding action keywords.
Here it's `navigation.jump.back` and `navigation.jump.forward`
https://github.com/hoppscotch/hoppscotch/blob/728515c2255692f8a6a2cbe8866bd8d5e418d2cf/packages/hoppscotch-app/helpers/actions.ts#L30-L31

`default.vue` defines the corresponding action handlers.

https://github.com/hoppscotch/hoppscotch/blob/dcbb17b1642d07da0a22ef3171e4572dd82dd93d/packages/hoppscotch-app/layouts/default.vue#L127-L132

A universal fix to actions interfering the native behaviors like navigate per word is to disable them when the focus is in `textareas`, `input`, `contenteditable` etc. This has been already implemented in `isTypableElement()` in `dom.ts`.

https://github.com/hoppscotch/hoppscotch/blob/dcbb17b1642d07da0a22ef3171e4572dd82dd93d/packages/hoppscotch-app/helpers/utils/dom.ts#L5-L19

Guess this will be helpful.

**Comment by deepto98** [comment] 2021-09-30 05:36
@liyasthomas Hi, I'd like to work on this issue. If it isn't assigned already, can you please assign this to me?

**Comment by mandaputtra** [comment] 2021-09-30 05:42
Go ahead if you want. I actually want to work on this weekend. Got so much to do on weekday :((

**Comment by deepto98** [comment] 2021-09-30 05:47
@mandaputtra Okay, sure. I also have some work during the week . Will try to work on this once I'm free and keep you updated.

**Comment by JeremyJaydan** [comment] 2021-10-01 02:03
Was about to make an issue on this, I'm keen for a solution! :)

**Comment by Sayan-dev** [comment] 2021-10-04 02:07
I can finish this up on weekdays I hope and if you don't mind @deepto98

**Comment by rishabhkalra96** [comment] 2021-10-08 17:36
> on branch main, I don't own mac so i don't know if that is a preferred or not. Just make sure whenever you're on body or input ctrl + arrow right/left doesn't change routes

thanks for the reply. I looked into the changes and found out that the below conditions on line 99 are letting the meta + event  reach default jumpActions. Removing the **not conditions** fixed the issue.

https://github.com/rishabhkalra96/hoppscotch/blob/d2b39976ba270ed3fb4c729f4782ae591260b741/packages/hoppscotch-app/helpers/keybindings.ts#L93-L111

https://github.com/rishabhkalra96/hoppscotch/blob/d2b39976ba270ed3fb4c729f4782ae591260b741/packages/hoppscotch-app/layouts/default.vue#L109-L133

Also, note that the issue is not just in linux, its consistent with all browsers. Since i don't own windows, so cant really tell about it but on mac its reproducible as in ubuntu (both on chrome and brave).

**Closed** 2021-10-09 01:16 UTC
Labels: bug, good first issue, hacktoberfest
