### ISSUE TITLE
How to host this on heroku or github pages?

### ISSUE THREAD

**Issue by dhruvitp-nimblechapps** [hoppscotch/hoppscotch#2590] opened 2022-08-17 12:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Have hosted this on github pages but it is not working https://nimblechapps.github.io/nimble-postie/

### Steps to reproduce

https://nimblechapps.github.io/nimble-postie/

### Environment

Production

### Version

Self-hosted

**Comment by liyasthomas** [comment] 2022-08-18 02:27
Possibly a duplicate of #1817.

**Closed by liyasthomas** 2022-08-18 02:27 UTC
Labels: bug, need testing
