### ISSUE TITLE
[feature]: Tabs on top 

### ISSUE THREAD

**Issue by ravi-sankarp** [hoppscotch/hoppscotch#2572] opened 2022-08-10 10:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Include tabs for easy switching between saved requests.Currently we have to select each saved request from the right sidebar.
If tabs are included on top of the send request section it would be more convenient.

It would help in easy navigation and increase productivity of the users.

### Why should this be worked on?

This feature could definitely benefit we fellow users.

**Comment by AndrewBastin** [comment] 2022-08-10 10:34
Closing as this is a duplicate of #690

**Closed by AndrewBastin** 2022-08-10 10:34 UTC
Labels: feature

**Comment by ravi-sankarp** [comment] 2022-08-10 12:04
Sorry for the inconvenience.I should have searched existing issues before opening a new one.
