### ISSUE TITLE
[bug]: Hoppscotch doesn't load in French since last version

### ISSUE THREAD

**Issue by JulienPerrin** [hoppscotch/hoppscotch#4002] opened 2024-04-23 12:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

All white when French language is selected for me (already selected before by me, which makes bug hard to comprehend). 
This bug took me 2 hours to find a solution : 
![image](https://github.com/hoppscotch/hoppscotch/assets/7848947/e107040b-ca37-4e9c-b2fc-14edc4f6b16b)

Here are my settings when I have the bug (need to click on settings button and do F5 : 
![image](https://github.com/hoppscotch/hoppscotch/assets/7848947/9dcb06b8-96be-4541-b621-6475d93c5f80)

Works when I switch to English : 
![image](https://github.com/hoppscotch/hoppscotch/assets/7848947/217e1000-b27d-46d5-9565-e215b9fec3a7)

works ok in English : 
![image](https://github.com/hoppscotch/hoppscotch/assets/7848947/d30b1559-db3a-4623-b93f-97036b8be555)

### Steps to reproduce

1. go to settings
2. switch to language "Français"
3. go to home page
4. see that it does not load

### Environment

Production
I use Chrome on Linux, but I suspect that it is not the issue. 

### Version

Cloud

**Comment by liyasthomas** [comment] 2024-04-23 14:06
Thanks for reporting this bug. Currently, we're investigating the root cause for this behavior, this is probably due to a misconfigured translation string in the French locale as mentioned.

I'll update once a fix is live on production.

**Comment by gabrielstuff** [comment] 2024-04-23 21:00
Yes, I confirm that I have the same issue in french.

I've needed to use an extension to switch the browser to english, then went to hoppscotch settings and select english and it worked !

I'm sing hoppscotch as a PWA.

**Comment by JoelJacobStephen** [comment] 2024-04-24 06:18
We have identified the cause of the issue and will be raising a fix for this soon.

**Comment by JulienPerrin** [comment] 2024-04-24 10:14
Thank you, would be nice if this kind of error was caught at compile time to avoid new issues.

**Comment by DataHearth** [comment] 2024-04-29 11:12
Found the same issue with the desktop app on MacOS. Probably the same under linux with the appimage.

**Comment by JoelJacobStephen** [comment] 2024-05-01 02:15
@JulienPerrin @DataHearth @gabrielstuff The fix has been merged in our latest release (`2024.3.2`). Can you cross-verify  if the issue has been resolved in the latest build?

**Comment by DataHearth** [comment] 2024-05-01 07:56
@JulienPerrin Hey! I can confirm on MacOS x64, the issue is gone, good job! I'm updating the package under nixpkgs 👍 . Gonna check with linux x64 today as well

**Comment by liyasthomas** [comment] 2024-05-01 08:09
Thanks for your patience and valuable feedback. This issue has been resolved in the latest release.

Closing this ticket as the fix is now available in the recent version. Please feel free to reach out if you have any other concerns.

**Closed by liyasthomas** 2024-05-01 08:09 UTC
Labels: bug, need testing

**Comment by JulienPerrin** [comment] 2024-05-14 07:25
solved for me, thank you
